(function(){function d(a){throw a;}var g=void 0,i=!0,l=null,n=!1;function aa(){return function(a){return a}}function o(){return function(){}}function p(a){return function(b){this[a]=b}}function q(a){return function(){return this[a]}}function u(a){return function(){return a}}var w,y=y||{};y.global=this;y.Oz=n;y.HM="en";y.UO=function(a){y.qG(a)};y.dP=function(a){y.Oz||(a=a||"",d(Error("Importing test-only code into non-debug environment"+a?": "+a:".")))};
y.qG=function(a,b,c){a=a.split(".");c=c||y.global;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)!a.length&&y.$n(b)?c[e]=b:c=c[e]?c[e]:c[e]={}};y.AK=function(){for(var a=["window","event"],b=y.global,c;c=a.shift();)if(y.OK(b[c]))b=b[c];else return l;return b};y.nO=function(a,b){var c=b||y.global,e;for(e in a)c[e]=a[e]};y.iN=o();y.rM=i;y.ZO=o();y.vN="";y.bI=o();y.sO=aa();y.ja=function(){d(Error("unimplemented abstract method"))};
y.jN=function(a){a.bO=function(){return a.LK||(a.LK=new a)}};
y.Yi=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};y.$n=function(a){return a!==g};y.AO=function(a){return a===l};y.OK=function(a){return a!=l};y.isArray=function(a){return"array"==y.Yi(a)};y.ze=function(a){var b=y.Yi(a);return"array"==b||"object"==b&&"number"==typeof a.length};y.yO=function(a){return y.qm(a)&&"function"==typeof a.getFullYear};y.uc=function(a){return"string"==typeof a};y.NK=function(a){return"boolean"==typeof a};y.tH=function(a){return"number"==typeof a};
y.rx=function(a){return"function"==y.Yi(a)};y.qm=function(a){var b=typeof a;return"object"==b&&a!=l||"function"==b};y.cm=function(a){return a[y.kv]||(a[y.kv]=++y.JL)};y.uL=function(a){"removeAttribute"in a&&a.removeAttribute(y.kv);try{delete a[y.kv]}catch(b){}};y.kv="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36);y.JL=0;y.$N=y.cm;y.XO=y.uL;y.EJ=function(a){var b=y.Yi(a);if("object"==b||"array"==b){if(a.pa)return a.pa();var b="array"==b?[]:{},c;for(c in a)b[c]=y.EJ(a[c]);return b}return a};
y.AJ=function(a,b,c){return a.call.apply(a.bind,arguments)};y.zJ=function(a,b,c){a||d(Error());if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};y.bind=function(a,b,c){y.bind=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?y.AJ:y.zJ;return y.bind.apply(l,arguments)};
y.kI=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};y.JO=function(a,b){for(var c in b)a[c]=b[c]};y.now=Date.now||function(){return+new Date};
y.mO=function(a){if(y.global.execScript)y.global.execScript(a,"JavaScript");else if(y.global.eval)if(y.vw==l&&(y.global.eval("var _et_ = 1;"),"undefined"!=typeof y.global._et_?(delete y.global._et_,y.vw=i):y.vw=n),y.vw)y.global.eval(a);else{var b=y.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=n;c.appendChild(b.createTextNode(a));b.body.appendChild(c);b.body.removeChild(c)}else d(Error("goog.globalEval not available"))};y.vw=l;
y.ZN=function(a,b){function c(a){return y.OF[a]||a}var e;e=y.OF?"BY_WHOLE"==y.OJ?c:function(a){for(var a=a.split("-"),b=[],e=0;e<a.length;e++)b.push(c(a[e]));return b.join("-")}:aa();return b?a+"-"+e(b):e(a)};y.$O=function(a,b){y.OF=a;y.OJ=b};y.eO=function(a,b){var c=b||{},e;for(e in c)var f=(""+c[e]).replace(/\$/g,"$$$$"),a=a.replace(RegExp("\\{\\$"+e+"\\}","gi"),f);return a};y.eg=function(a,b){y.qG(a,b,g)};y.K=function(a,b,c){a[b]=c};
y.b=function(a,b){function c(){}c.prototype=b.prototype;a.e=b.prototype;a.prototype=new c;a.prototype.constructor=a};y.uN=function(a,b,c){var e=arguments.callee.caller;if(e.e)return e.e.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var f=Array.prototype.slice.call(arguments,2),h=n,j=a.constructor;j;j=j.e&&j.e.constructor)if(j.prototype[b]===e)h=i;else if(h)return j.prototype[b].apply(a,f);if(a[b]===e)return a.constructor.prototype[b].apply(a,f);d(Error("goog.base called from a method of one name to a method of a different name"))};
y.scope=function(a){a.call(y.global)};y.debug={};function ba(a){this.stack=Error().stack||"";a&&(this.message=""+a)}y.b(ba,Error);ba.prototype.name="CustomError";y.J={};y.J.EL=function(a){return 0==a.lastIndexOf("/",0)};y.J.hK=function(a){var b=a.length-1;return 0<=b&&a.indexOf("/",b)==b};y.J.EN=function(a,b){return 0==y.J.rF(b,a.substr(0,b.length))};y.J.DN=function(a,b){return 0==y.J.rF(b,a.substr(a.length-b.length,b.length))};y.J.FL=function(a,b){for(var c=1;c<arguments.length;c++)var e=(""+arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,e);return a};y.J.IN=function(a){return a.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")};y.J.Hh=function(a){return/^[\s\xa0]*$/.test(a)};
y.J.zO=function(a){return y.J.Hh(y.J.YK(a))};y.J.xO=function(a){return!/[^\t\n\r ]/.test(a)};y.J.vO=function(a){return!/[^a-zA-Z]/.test(a)};y.J.BO=function(a){return!/[^0-9]/.test(a)};y.J.wO=function(a){return!/[^a-zA-Z0-9]/.test(a)};y.J.DO=function(a){return" "==a};y.J.EO=function(a){return 1==a.length&&" "<=a&&"~">=a||"\u0080"<=a&&"\ufffd">=a};y.J.iP=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")};y.J.CN=function(a){return a.replace(/(\r\n|\r|\n)/g,"\n")};
y.J.NO=function(a){return a.replace(/\xa0|\s/g," ")};y.J.MO=function(a){return a.replace(/\xa0|[ \t]+/g," ")};y.J.HN=function(a){return a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"")};y.J.trim=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};y.J.trimLeft=function(a){return a.replace(/^[\s\xa0]+/,"")};y.J.trimRight=function(a){return a.replace(/[\s\xa0]+$/,"")};y.J.rF=function(a,b){var c=(""+a).toLowerCase(),e=(""+b).toLowerCase();return c<e?-1:c==e?0:1};y.J.dI=/(\.\d+)|(\d+)|(\D+)/g;
y.J.OO=function(a,b){if(a==b)return 0;if(!a)return-1;if(!b)return 1;for(var c=a.toLowerCase().match(y.J.dI),e=b.toLowerCase().match(y.J.dI),f=Math.min(c.length,e.length),h=0;h<f;h++){var j=c[h],k=e[h];if(j!=k)return c=parseInt(j,10),!isNaN(c)&&(e=parseInt(k,10),!isNaN(e)&&c-e)?c-e:j<k?-1:1}return c.length!=e.length?c.length-e.length:a<b?-1:1};y.J.gK=/^[a-zA-Z0-9\-_.!~*'()]*$/;y.J.Ar=function(a){a=""+a;return!y.J.gK.test(a)?encodeURIComponent(a):a};
y.J.yz=function(a){return decodeURIComponent(a.replace(/\+/g," "))};y.J.cL=function(a,b){return a.replace(/(\r\n|\r|\n)/g,b?"<br />":"<br>")};y.J.YG=function(a){if(!y.J.vJ.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(y.J.wJ,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(y.J.XK,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(y.J.FK,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(y.J.nL,"&quot;"));return a};y.J.wJ=/&/g;y.J.XK=/</g;y.J.FK=/>/g;y.J.nL=/\"/g;y.J.vJ=/[&<>\"]/;
y.J.aJ=function(a){return y.J.contains(a,"&")?"document"in y.global?y.J.KL(a):y.J.LL(a):a};y.J.KL=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c=document.createElement("div");return a.replace(y.J.qJ,function(a,f){var h=b[a];if(h)return h;if("#"==f.charAt(0)){var j=Number("0"+f.substr(1));isNaN(j)||(h=String.fromCharCode(j))}h||(c.innerHTML=a+" ",h=c.firstChild.nodeValue.slice(0,-1));return b[a]=h})};
y.J.LL=function(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var e=Number("0"+c.substr(1));if(!isNaN(e))return String.fromCharCode(e)}return a}})};y.J.qJ=/&([^;\s<&]+);?/g;y.J.vP=function(a,b){return y.J.cL(a.replace(/  /g," &#160;"),b)};
y.J.jP=function(a,b){for(var c=b.length,e=0;e<c;e++){var f=1==c?b:b.charAt(e);if(a.charAt(0)==f&&a.charAt(a.length-1)==f)return a.substring(1,a.length-1)}return a};y.J.truncate=function(a,b,c){c&&(a=y.J.aJ(a));a.length>b&&(a=a.substring(0,b-3)+"...");c&&(a=y.J.YG(a));return a};
y.J.pP=function(a,b,c,e){c&&(a=y.J.aJ(a));if(e&&a.length>b)e>b&&(e=b),a=a.substring(0,b-e)+"..."+a.substring(a.length-e);else if(a.length>b)var e=Math.floor(b/2),f=a.length-e,a=a.substring(0,e+b%2)+"..."+a.substring(f);c&&(a=y.J.YG(a));return a};y.J.rE={"\x00":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"};y.J.Cx={"'":"\\'"};
y.J.quote=function(a){a=""+a;if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var e=a.charAt(c),f=e.charCodeAt(0);b[c+1]=y.J.rE[e]||(31<f&&127>f?e:y.J.mG(e))}b.push('"');return b.join("")};y.J.RN=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=y.J.mG(a.charAt(c));return b.join("")};
y.J.mG=function(a){if(a in y.J.Cx)return y.J.Cx[a];if(a in y.J.rE)return y.J.Cx[a]=y.J.rE[a];var b=a,c=a.charCodeAt(0);if(31<c&&127>c)b=a;else{if(256>c){if(b="\\x",16>c||256<c)b+="0"}else b="\\u",4096>c&&(b+="0");b+=c.toString(16).toUpperCase()}return y.J.Cx[a]=b};y.J.mP=function(a){for(var b={},c=0;c<a.length;c++)b[a.charAt(c)]=i;return b};y.J.contains=function(a,b){return-1!=a.indexOf(b)};y.J.KN=function(a,b){return a&&b?a.split(b).length-1:0};
y.J.ty=function(a,b,c){var e=a;0<=b&&b<a.length&&0<c&&(e=a.substr(0,b)+a.substr(b+c,a.length-b-c));return e};y.J.remove=function(a,b){var c=RegExp(y.J.uI(b),"");return a.replace(c,"")};y.J.xI=function(a,b){var c=RegExp(y.J.uI(b),"g");return a.replace(c,"")};y.J.uI=function(a){return(""+a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};y.J.repeat=function(a,b){return Array(b+1).join(a)};
y.J.QO=function(a,b,c){a=y.$n(c)?a.toFixed(c):""+a;c=a.indexOf(".");-1==c&&(c=a.length);return y.J.repeat("0",Math.max(0,b-c))+a};y.J.YK=function(a){return a==l?"":""+a};y.J.BJ=function(a){return Array.prototype.join.call(arguments,"")};y.J.NG=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^y.now()).toString(36)};
y.J.yF=function(a,b){for(var c=0,e=y.J.trim(""+a).split("."),f=y.J.trim(""+b).split("."),h=Math.max(e.length,f.length),j=0;0==c&&j<h;j++){var k=e[j]||"",m=f[j]||"",s=RegExp("(\\d*)(\\D*)","g"),t=RegExp("(\\d*)(\\D*)","g");do{var v=s.exec(k)||["","",""],x=t.exec(m)||["","",""];if(0==v[0].length&&0==x[0].length)break;c=y.J.CA(0==v[1].length?0:parseInt(v[1],10),0==x[1].length?0:parseInt(x[1],10))||y.J.CA(0==v[2].length,0==x[2].length)||y.J.CA(v[2],x[2])}while(0==c)}return c};
y.J.CA=function(a,b){return a<b?-1:a>b?1:0};y.J.pJ=4294967296;y.J.qO=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=y.J.pJ;return b};y.J.NL=2147483648*Math.random()|0;y.J.MN=function(){return"goog_"+y.J.NL++};y.J.nP=function(a){var b=Number(a);return 0==b&&y.J.Hh(a)?NaN:b};y.J.XI={};y.J.lP=function(a){return y.J.XI[a]||(y.J.XI[a]=(""+a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};y.J.YI={};
y.J.oP=function(a){return y.J.YI[a]||(y.J.YI[a]=(""+a).replace(/([A-Z])/g,"-$1").toLowerCase())};y.Cc={};y.Cc.ek=y.Oz;function ca(a,b){b.unshift(a);ba.call(this,y.J.FL.apply(l,b));b.shift()}y.b(ca,ba);ca.prototype.name="AssertionError";y.Cc.Pl=function(a,b,c,e){var f="Assertion failed";if(c)var f=f+(": "+c),h=e;else a&&(f+=": "+a,h=b);d(new ca(""+f,h||[]))};y.Cc.assert=function(a,b,c){y.Cc.ek&&!a&&y.Cc.Pl("",l,b,Array.prototype.slice.call(arguments,2));return a};y.Cc.TN=function(a,b){y.Cc.ek&&d(new ca("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};
y.Cc.rN=function(a,b,c){y.Cc.ek&&!y.tH(a)&&y.Cc.Pl("Expected number but got %s: %s.",[y.Yi(a),a],b,Array.prototype.slice.call(arguments,2));return a};y.Cc.tN=function(a,b,c){y.Cc.ek&&!y.uc(a)&&y.Cc.Pl("Expected string but got %s: %s.",[y.Yi(a),a],b,Array.prototype.slice.call(arguments,2));return a};y.Cc.pN=function(a,b,c){y.Cc.ek&&!y.rx(a)&&y.Cc.Pl("Expected function but got %s: %s.",[y.Yi(a),a],b,Array.prototype.slice.call(arguments,2));return a};
y.Cc.sN=function(a,b,c){y.Cc.ek&&!y.qm(a)&&y.Cc.Pl("Expected object but got %s: %s.",[y.Yi(a),a],b,Array.prototype.slice.call(arguments,2));return a};y.Cc.nN=function(a,b,c){y.Cc.ek&&!y.isArray(a)&&y.Cc.Pl("Expected array but got %s: %s.",[y.Yi(a),a],b,Array.prototype.slice.call(arguments,2));return a};y.Cc.oN=function(a,b,c){y.Cc.ek&&!y.NK(a)&&y.Cc.Pl("Expected boolean but got %s: %s.",[y.Yi(a),a],b,Array.prototype.slice.call(arguments,2));return a};
y.Cc.qN=function(a,b,c,e){y.Cc.ek&&!(a instanceof b)&&y.Cc.Pl("instanceof check failed.",l,c,Array.prototype.slice.call(arguments,3))};y.O={};y.gn=i;y.O.RO=function(a){return a[a.length-1]};y.O.qd=Array.prototype;y.O.indexOf=y.gn&&y.O.qd.indexOf?function(a,b,c){return y.O.qd.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(y.uc(a))return!y.uc(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
y.O.lastIndexOf=y.gn&&y.O.qd.lastIndexOf?function(a,b,c){return y.O.qd.lastIndexOf.call(a,b,c==l?a.length-1:c)}:function(a,b,c){c=c==l?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(y.uc(a))return!y.uc(b)||1!=b.length?-1:a.lastIndexOf(b,c);for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};y.O.forEach=y.gn&&y.O.qd.forEach?function(a,b,c){y.O.qd.forEach.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=y.uc(a)?a.split(""):a,h=0;h<e;h++)h in f&&b.call(c,f[h],h,a)};
y.O.lK=function(a,b){for(var c=a.length,e=y.uc(a)?a.split(""):a,c=c-1;0<=c;--c)c in e&&b.call(g,e[c],c,a)};y.O.filter=y.gn&&y.O.qd.filter?function(a,b,c){return y.O.qd.filter.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=[],h=0,j=y.uc(a)?a.split(""):a,k=0;k<e;k++)if(k in j){var m=j[k];b.call(c,m,k,a)&&(f[h++]=m)}return f};
y.O.map=y.gn&&y.O.qd.map?function(a,b,c){return y.O.qd.map.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=Array(e),h=y.uc(a)?a.split(""):a,j=0;j<e;j++)j in h&&(f[j]=b.call(c,h[j],j,a));return f};y.O.reduce=function(a,b,c,e){if(a.reduce)return e?a.reduce(y.bind(b,e),c):a.reduce(b,c);var f=c;y.O.forEach(a,function(c,j){f=b.call(e,f,c,j,a)});return f};
y.O.reduceRight=function(a,b,c,e){if(a.reduceRight)return e?a.reduceRight(y.bind(b,e),c):a.reduceRight(b,c);var f=c;y.O.lK(a,function(c,j){f=b.call(e,f,c,j,a)});return f};y.O.some=y.gn&&y.O.qd.some?function(a,b,c){return y.O.qd.some.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=y.uc(a)?a.split(""):a,h=0;h<e;h++)if(h in f&&b.call(c,f[h],h,a))return i;return n};
y.O.every=y.gn&&y.O.qd.every?function(a,b,c){return y.O.qd.every.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=y.uc(a)?a.split(""):a,h=0;h<e;h++)if(h in f&&!b.call(c,f[h],h,a))return n;return i};y.O.find=function(a,b,c){b=y.O.uG(a,b,c);return 0>b?l:y.uc(a)?a.charAt(b):a[b]};y.O.uG=function(a,b,c){for(var e=a.length,f=y.uc(a)?a.split(""):a,h=0;h<e;h++)if(h in f&&b.call(c,f[h],h,a))return h;return-1};y.O.UN=function(a,b,c){b=y.O.iK(a,b,c);return 0>b?l:y.uc(a)?a.charAt(b):a[b]};
y.O.iK=function(a,b,c){for(var e=a.length,f=y.uc(a)?a.split(""):a,e=e-1;0<=e;e--)if(e in f&&b.call(c,f[e],e,a))return e;return-1};y.O.contains=function(a,b){return 0<=y.O.indexOf(a,b)};y.O.Hh=function(a){return 0==a.length};y.O.clear=function(a){if(!y.isArray(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0};y.O.tO=function(a,b){y.O.contains(a,b)||a.push(b)};y.O.dH=function(a,b,c){y.O.splice(a,c,0,b)};y.O.uO=function(a,b,c){y.kI(y.O.splice,a,c,0).apply(l,b)};
y.O.insertBefore=function(a,b,c){var e;2==arguments.length||0>(e=y.O.indexOf(a,c))?a.push(b):y.O.dH(a,b,e)};y.O.remove=function(a,b){var c=y.O.indexOf(a,b),e;(e=0<=c)&&y.O.ty(a,c);return e};y.O.ty=function(a,b){return 1==y.O.qd.splice.call(a,b,1).length};y.O.YO=function(a,b,c){b=y.O.uG(a,b,c);return 0<=b?(y.O.ty(a,b),i):n};y.O.concat=function(a){return y.O.qd.concat.apply(y.O.qd,arguments)};y.O.pa=function(a){if(y.isArray(a))return y.O.concat(a);for(var b=[],c=0,e=a.length;c<e;c++)b[c]=a[c];return b};
y.O.JE=function(a){return y.isArray(a)?y.O.concat(a):y.O.pa(a)};y.O.extend=function(a,b){for(var c=1;c<arguments.length;c++){var e=arguments[c],f;if(y.isArray(e)||(f=y.ze(e))&&e.hasOwnProperty("callee"))a.push.apply(a,e);else if(f)for(var h=a.length,j=e.length,k=0;k<j;k++)a[h+k]=e[k];else a.push(e)}};y.O.splice=function(a,b,c,e){return y.O.qd.splice.apply(a,y.O.slice(arguments,1))};y.O.slice=function(a,b,c){return 2>=arguments.length?y.O.qd.slice.call(a,b):y.O.qd.slice.call(a,b,c)};
y.O.WO=function(a,b){for(var c=b||a,e={},f=0,h=0;h<a.length;){var j=a[h++],k=y.qm(j)?"o"+y.cm(j):(typeof j).charAt(0)+j;Object.prototype.hasOwnProperty.call(e,k)||(e[k]=i,c[f++]=j)}c.length=f};y.O.kF=function(a,b,c){return y.O.lF(a,c||y.O.Bn,n,b)};y.O.yN=function(a,b,c){return y.O.lF(a,b,i,g,c)};y.O.lF=function(a,b,c,e,f){for(var h=0,j=a.length,k;h<j;){var m=h+j>>1,s;s=c?b.call(f,a[m],m,a):b(e,a[m]);0<s?h=m+1:(j=m,k=!s)}return k?h:~h};y.O.sort=function(a,b){y.O.qd.sort.call(a,b||y.O.Bn)};
y.O.hP=function(a,b){for(var c=0;c<a.length;c++)a[c]={index:c,value:a[c]};var e=b||y.O.Bn;y.O.sort(a,function(a,b){return e(a.value,b.value)||a.index-b.index});for(c=0;c<a.length;c++)a[c]=a[c].value};y.O.gP=function(a,b,c){var e=c||y.O.Bn;y.O.sort(a,function(a,c){return e(a[b],c[b])})};y.O.CO=function(a,b,c){for(var b=b||y.O.Bn,e=1;e<a.length;e++){var f=b(a[e-1],a[e]);if(0<f||0==f&&c)return n}return i};
y.O.kB=function(a,b,c){if(!y.ze(a)||!y.ze(b)||a.length!=b.length)return n;for(var e=a.length,c=c||y.O.SJ,f=0;f<e;f++)if(!c(a[f],b[f]))return n;return i};y.O.GJ=function(a,b,c){return y.O.kB(a,b,c)};y.O.JN=function(a,b,c){for(var c=c||y.O.Bn,e=Math.min(a.length,b.length),f=0;f<e;f++){var h=c(a[f],b[f]);if(0!=h)return h}return y.O.Bn(a.length,b.length)};y.O.Bn=function(a,b){return a>b?1:a<b?-1:0};y.O.SJ=function(a,b){return a===b};
y.O.wN=function(a,b,c){c=y.O.kF(a,b,c);return 0>c?(y.O.dH(a,b,-(c+1)),i):n};y.O.xN=function(a,b,c){b=y.O.kF(a,b,c);return 0<=b?y.O.ty(a,b):n};y.O.zN=function(a,b){for(var c={},e=0;e<a.length;e++){var f=a[e],h=b(f,e,a);y.$n(h)&&(c[h]||(c[h]=[])).push(f)}return c};y.O.repeat=function(a,b){for(var c=[],e=0;e<b;e++)c[e]=a;return c};y.O.kK=function(a){for(var b=[],c=0;c<arguments.length;c++){var e=arguments[c];y.isArray(e)?b.push.apply(b,y.O.kK.apply(l,e)):b.push(e)}return b};
y.O.rotate=function(a,b){a.length&&(b%=a.length,0<b?y.O.qd.unshift.apply(a,a.splice(-b,b)):0>b&&y.O.qd.push.apply(a,a.splice(0,-b)));return a};y.O.wP=function(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var e=[],f=0;f<arguments.length;f++){var h=arguments[f];if(c>=h.length)return b;e.push(h[c])}b.push(e)}};y.O.fP=function(a,b){for(var c=b||Math.random,e=a.length-1;0<e;e--){var f=Math.floor(c()*(e+1)),h=a[e];a[e]=a[f];a[f]=h}};y.debug.we={};y.debug.tM=o();y.debug.we.Yq=[];y.debug.we.iD=[];y.debug.we.RH=n;y.debug.we.vI=function(a){y.debug.we.Yq[y.debug.we.Yq.length]=a;if(y.debug.we.RH)for(var b=y.debug.we.iD,c=0;c<b.length;c++)a(y.bind(b[c].WL,b[c]))};y.debug.we.KO=function(a){y.debug.we.RH=i;for(var b=y.bind(a.WL,a),c=0;c<y.debug.we.Yq.length;c++)y.debug.we.Yq[c](b);y.debug.we.iD.push(a)};y.debug.we.rP=function(a){for(var b=y.debug.we.iD,a=y.bind(a.tP,a),c=0;c<y.debug.we.Yq.length;c++)y.debug.we.Yq[c](a);b.length--};y.debug.QN={pI:aa()};y.userAgent={};y.userAgent.XE=n;y.userAgent.WE=n;y.userAgent.aF=n;y.userAgent.Mz=n;y.userAgent.$E=n;y.userAgent.jJ=n;y.userAgent.hp=y.userAgent.XE||y.userAgent.WE||y.userAgent.Mz||y.userAgent.aF||y.userAgent.$E;y.userAgent.TG=function(){return y.global.navigator?y.global.navigator.userAgent:l};y.userAgent.Pw=function(){return y.global.navigator};
y.userAgent.KK=function(){y.userAgent.Fs=n;y.userAgent.XF=n;y.userAgent.ow=n;y.userAgent.YF=n;y.userAgent.WF=n;var a;if(!y.userAgent.hp&&(a=y.userAgent.TG())){var b=y.userAgent.Pw();y.userAgent.Fs=0==a.indexOf("Opera");y.userAgent.XF=!y.userAgent.Fs&&-1!=a.indexOf("MSIE");y.userAgent.ow=!y.userAgent.Fs&&-1!=a.indexOf("WebKit");y.userAgent.YF=y.userAgent.ow&&-1!=a.indexOf("Mobile");y.userAgent.WF=!y.userAgent.Fs&&!y.userAgent.ow&&"Gecko"==b.product}};y.userAgent.hp||y.userAgent.KK();
y.userAgent.Pz=y.userAgent.hp?y.userAgent.$E:y.userAgent.Fs;y.userAgent.$i=y.userAgent.hp?y.userAgent.XE:y.userAgent.XF;y.userAgent.fv=y.userAgent.hp?y.userAgent.WE:y.userAgent.WF;y.userAgent.tl=y.userAgent.hp?y.userAgent.aF||y.userAgent.Mz:y.userAgent.ow;y.userAgent.NM=y.userAgent.Mz||y.userAgent.YF;y.userAgent.WM=y.userAgent.tl;y.userAgent.ZJ=function(){var a=y.userAgent.Pw();return a&&a.platform||""};y.userAgent.Qz=y.userAgent.ZJ();y.userAgent.ZE=n;y.userAgent.bF=n;y.userAgent.YE=n;
y.userAgent.cF=n;y.userAgent.Sr=y.userAgent.ZE||y.userAgent.bF||y.userAgent.YE||y.userAgent.cF;y.userAgent.JK=function(){y.userAgent.WJ=y.J.contains(y.userAgent.Qz,"Mac");y.userAgent.XJ=y.J.contains(y.userAgent.Qz,"Win");y.userAgent.VJ=y.J.contains(y.userAgent.Qz,"Linux");y.userAgent.YJ=!!y.userAgent.Pw()&&y.J.contains(y.userAgent.Pw().appVersion||"","X11")};y.userAgent.Sr||y.userAgent.JK();y.userAgent.JM=y.userAgent.Sr?y.userAgent.ZE:y.userAgent.WJ;y.userAgent.gN=y.userAgent.Sr?y.userAgent.bF:y.userAgent.XJ;
y.userAgent.FM=y.userAgent.Sr?y.userAgent.YE:y.userAgent.VJ;y.userAgent.hN=y.userAgent.Sr?y.userAgent.cF:y.userAgent.YJ;y.userAgent.$J=function(){var a="",b;y.userAgent.Pz&&y.global.opera?(a=y.global.opera.version,a="function"==typeof a?a():a):(y.userAgent.fv?b=/rv\:([^\);]+)(\)|;)/:y.userAgent.$i?b=/MSIE\s+([^\);]+)(\)|;)/:y.userAgent.tl&&(b=/WebKit\/(\S+)/),b&&(a=(a=b.exec(y.userAgent.TG()))?a[1]:""));return y.userAgent.$i&&(b=y.userAgent.tK(),b>parseFloat(a))?""+b:a};
y.userAgent.tK=function(){var a=y.global.document;return a?a.documentMode:g};y.userAgent.VERSION=y.userAgent.$J();y.userAgent.GJ=function(a,b){return y.J.yF(a,b)};y.userAgent.EH={};y.userAgent.fo=function(a){return y.userAgent.jJ||y.userAgent.EH[a]||(y.userAgent.EH[a]=0<=y.J.yF(y.userAgent.VERSION,a))};y.userAgent.kH={};y.userAgent.jH=function(){return y.userAgent.kH[9]||(y.userAgent.kH[9]=y.userAgent.$i&&!!document.documentMode&&9<=document.documentMode)};y.B={};!y.userAgent.$i||y.userAgent.jH();var ea=!y.userAgent.$i||y.userAgent.jH(),fa=y.userAgent.$i&&!y.userAgent.fo("8");!y.userAgent.tl||y.userAgent.fo("528");y.userAgent.fv&&y.userAgent.fo("1.9b")||y.userAgent.$i&&y.userAgent.fo("8")||y.userAgent.Pz&&y.userAgent.fo("9.5")||y.userAgent.tl&&y.userAgent.fo("528");!y.userAgent.fv||y.userAgent.fo("8");y.aK={};y.aK.AM=o();function ga(){}ga.prototype.dG=n;ga.prototype.si=function(){this.dG||(this.dG=i,this.Ol())};ga.prototype.Ol=function(){this.TJ&&y.cG.apply(l,this.TJ)};y.si=function(a){a&&"function"==typeof a.si&&a.si()};y.cG=function(a){for(var b=0,c=arguments.length;b<c;++b){var e=arguments[b];y.ze(e)?y.cG.apply(l,e):y.si(e)}};function ha(a,b){this.type=a;this.currentTarget=this.target=b}y.b(ha,ga);w=ha.prototype;w.Ol=function(){delete this.type;delete this.target;delete this.currentTarget};w.Io=n;w.lu=i;w.stopPropagation=function(){this.Io=i};w.preventDefault=function(){this.lu=n};ha.stopPropagation=function(a){a.stopPropagation()};ha.preventDefault=function(a){a.preventDefault()};var z={Nz:"click",kM:"dblclick",fn:"mousedown",iv:"mouseup",hv:"mouseover",gv:"mouseout",ip:"mousemove",ZM:"selectstart",DM:"keypress",CM:"keydown",EM:"keyup",dM:"blur",vM:"focus",lM:"deactivate",wM:y.userAgent.$i?"focusin":"DOMFocusIn",xM:y.userAgent.$i?"focusout":"DOMFocusOut",fM:"change",YM:"select",$M:"submit",BM:"input",UM:"propertychange",pM:"dragstart",mM:"dragenter",oM:"dragover",nM:"dragleave",qM:"drop",dN:"touchstart",cN:"touchmove",bN:"touchend",aN:"touchcancel",hM:"contextmenu",sM:"error",
zM:"help",GM:"load",IM:"losecapture",VM:"readystatechange",jv:"resize",XM:"scroll",fN:"unload",yM:"hashchange",QM:"pagehide",RM:"pageshow",TM:"popstate",iM:"copy",SM:"paste",jM:"cut",aM:"beforecopy",bM:"beforecut",cM:"beforepaste",KM:"message",gM:"connect",eN:y.userAgent.tl?"webkitTransitionEnd":y.userAgent.Pz?"oTransitionEnd":"transitionend"};y.Jo={};y.Jo.object=function(a,b){return b};y.Jo.oE=function(a){y.Jo.oE[" "](a);return a};y.Jo.oE[" "]=y.bI;y.Jo.CJ=function(a){try{return y.Jo.oE(a.nodeName),i}catch(b){}return n};function ia(a,b){a&&this.Un(a,b)}y.b(ia,ha);w=ia.prototype;w.target=l;w.relatedTarget=l;w.offsetX=0;w.offsetY=0;w.clientX=0;w.clientY=0;w.screenX=0;w.screenY=0;w.button=0;w.keyCode=0;w.charCode=0;w.ctrlKey=n;w.altKey=n;w.shiftKey=n;w.metaKey=n;w.Sp=l;
w.Un=function(a,b){var c=this.type=a.type;ha.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;e?y.userAgent.fv&&(y.Jo.CJ(e)||(e=l)):c==z.hv?e=a.fromElement:c==z.gv&&(e=a.toElement);this.relatedTarget=e;this.offsetX=y.userAgent.tl||a.offsetX!==g?a.offsetX:a.layerX;this.offsetY=y.userAgent.tl||a.offsetY!==g?a.offsetY:a.layerY;this.clientX=a.clientX!==g?a.clientX:a.pageX;this.clientY=a.clientY!==g?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.Sp=a;delete this.lu;delete this.Io};w.stopPropagation=function(){ia.e.stopPropagation.call(this);this.Sp.stopPropagation?this.Sp.stopPropagation():this.Sp.cancelBubble=i};
w.preventDefault=function(){ia.e.preventDefault.call(this);var a=this.Sp;if(a.preventDefault)a.preventDefault();else if(a.returnValue=n,fa)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};w.Ol=function(){ia.e.Ol.call(this);this.relatedTarget=this.currentTarget=this.target=this.Sp=l};y.B.eF=o();y.B.eF.prototype.hb=o();y.B.eF.prototype.Lc=o();function ja(){}var ka=0;w=ja.prototype;w.key=0;w.Ko=n;w.uA=n;w.Un=function(a,b,c,e,f,h){y.rx(a)?this.oH=i:a&&a.handleEvent&&y.rx(a.handleEvent)?this.oH=n:d(Error("Invalid listener argument"));this.Iq=a;this.qI=b;this.src=c;this.type=e;this.capture=!!f;this.ax=h;this.uA=n;this.key=++ka;this.Ko=n};w.handleEvent=function(a){return this.oH?this.Iq.call(this.ax||this.src,a):this.Iq.handleEvent.call(this.Iq,a)};y.object={};y.object.forEach=function(a,b,c){for(var e in a)b.call(c,a[e],e,a)};y.object.filter=function(a,b,c){var e={},f;for(f in a)b.call(c,a[f],f,a)&&(e[f]=a[f]);return e};y.object.map=function(a,b,c){var e={},f;for(f in a)e[f]=b.call(c,a[f],f,a);return e};y.object.some=function(a,b,c){for(var e in a)if(b.call(c,a[e],e,a))return i;return n};y.object.every=function(a,b,c){for(var e in a)if(!b.call(c,a[e],e,a))return n;return i};y.object.bm=function(a){var b=0,c;for(c in a)b++;return b};
y.object.XN=function(a){for(var b in a)return b};y.object.YN=function(a){for(var b in a)return a[b]};y.object.contains=function(a,b){return y.object.Ip(a,b)};y.object.ff=function(a){var b=[],c=0,e;for(e in a)b[c++]=a[e];return b};y.object.Lf=function(a){var b=[],c=0,e;for(e in a)b[c++]=e;return b};y.object.lO=function(a,b){for(var c=y.ze(b),e=c?b:arguments,c=c?0:1;c<e.length&&!(a=a[e[c]],!y.$n(a));c++);return a};y.object.nj=function(a,b){return b in a};
y.object.Ip=function(a,b){for(var c in a)if(a[c]==b)return i;return n};y.object.jK=function(a,b,c){for(var e in a)if(b.call(c,a[e],e,a))return e};y.object.VN=function(a,b,c){return(b=y.object.jK(a,b,c))&&a[b]};y.object.Hh=function(a){for(var b in a)return n;return i};y.object.clear=function(a){for(var b in a)delete a[b]};y.object.remove=function(a,b){var c;(c=b in a)&&delete a[b];return c};
y.object.add=function(a,b,c){b in a&&d(Error('The object already contains the key "'+b+'"'));y.object.set(a,b,c)};y.object.get=function(a,b,c){return b in a?a[b]:c};y.object.set=function(a,b,c){a[b]=c};y.object.cP=function(a,b,c){return b in a?a[b]:a[b]=c};y.object.pa=function(a){var b={},c;for(c in a)b[c]=a[c];return b};y.object.OL=function(a){var b=y.Yi(a);if("object"==b||"array"==b){if(a.pa)return a.pa();var b="array"==b?[]:{},c;for(c in a)b[c]=y.object.OL(a[c]);return b}return a};
y.object.IL=function(a){var b={},c;for(c in a)b[a[c]]=c;return b};y.object.fF="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");y.object.extend=function(a,b){for(var c,e,f=1;f<arguments.length;f++){e=arguments[f];for(c in e)a[c]=e[c];for(var h=0;h<y.object.fF.length;h++)c=y.object.fF[h],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}};
y.object.create=function(a){var b=arguments.length;if(1==b&&y.isArray(arguments[0]))return y.object.create.apply(l,arguments[0]);b%2&&d(Error("Uneven number of arguments"));for(var c={},e=0;e<b;e+=2)c[arguments[e]]=arguments[e+1];return c};y.object.LJ=function(a){var b=arguments.length;if(1==b&&y.isArray(arguments[0]))return y.object.LJ.apply(l,arguments[0]);for(var c={},e=0;e<b;e++)c[arguments[e]]=i;return c};y.B.$L=n;y.B.Hd={};y.B.ng={};y.B.Xj={};y.B.iL="on";y.B.uD={};y.B.FO="_";
y.B.hb=function(a,b,c,e,f){if(b){if(y.isArray(b)){for(var h=0;h<b.length;h++)y.B.hb(a,b[h],c,e,f);return l}var e=!!e,j=y.B.ng;b in j||(j[b]={fc:0,Sh:0});j=j[b];e in j||(j[e]={fc:0,Sh:0},j.fc++);var j=j[e],k=y.cm(a),m;j.Sh++;if(j[k]){m=j[k];for(h=0;h<m.length;h++)if(j=m[h],j.Iq==c&&j.ax==f){if(j.Ko)break;return m[h].key}}else m=j[k]=[],j.fc++;h=y.B.DK();h.src=a;j=new ja;j.Un(c,h,a,b,e,f);c=j.key;h.key=c;m.push(j);y.B.Hd[c]=j;y.B.Xj[k]||(y.B.Xj[k]=[]);y.B.Xj[k].push(j);a.addEventListener?(a==y.global||
!a.PF)&&a.addEventListener(b,h,e):a.attachEvent(y.B.KG(b),h);return c}d(Error("Invalid event type"))};y.B.DK=function(){var a=y.B.gt,b=ea?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b};y.B.VK=function(a,b,c,e,f){if(y.isArray(b))for(var h=0;h<b.length;h++)y.B.VK(a,b[h],c,e,f);else a=y.B.hb(a,b,c,e,f),y.B.Hd[a].uA=i};y.B.GO=function(a,b,c,e,f){b.hb(a,c,e,f)};
y.B.Lc=function(a,b,c,e,f){if(y.isArray(b)){for(var h=0;h<b.length;h++)y.B.Lc(a,b[h],c,e,f);return l}e=!!e;a=y.B.KB(a,b,e);if(!a)return n;for(h=0;h<a.length;h++)if(a[h].Iq==c&&a[h].capture==e&&a[h].ax==f)return y.B.vz(a[h].key);return n};
y.B.vz=function(a){if(!y.B.Hd[a])return n;var b=y.B.Hd[a];if(b.Ko)return n;var c=b.src,e=b.type,f=b.qI,h=b.capture;c.removeEventListener?(c==y.global||!c.PF)&&c.removeEventListener(e,f,h):c.detachEvent&&c.detachEvent(y.B.KG(e),f);c=y.cm(c);f=y.B.ng[e][h][c];if(y.B.Xj[c]){var j=y.B.Xj[c];y.O.remove(j,b);0==j.length&&delete y.B.Xj[c]}b.Ko=i;f.$H=i;y.B.vF(e,h,c,f);delete y.B.Hd[a];return i};y.B.qP=function(a,b,c,e,f){b.Lc(a,c,e,f)};
y.B.vF=function(a,b,c,e){if(!e.Jx&&e.$H){for(var f=0,h=0;f<e.length;f++)e[f].Ko?e[f].qI.src=l:(f!=h&&(e[h]=e[f]),h++);e.length=h;e.$H=n;0==h&&(delete y.B.ng[a][b][c],y.B.ng[a][b].fc--,0==y.B.ng[a][b].fc&&(delete y.B.ng[a][b],y.B.ng[a].fc--),0==y.B.ng[a].fc&&delete y.B.ng[a])}};
y.B.xI=function(a,b,c){var e=0,f=b==l,h=c==l,c=!!c;if(a==l)y.object.forEach(y.B.Xj,function(a){for(var j=a.length-1;0<=j;j--){var k=a[j];if((f||b==k.type)&&(h||c==k.capture))y.B.vz(k.key),e++}});else if(a=y.cm(a),y.B.Xj[a])for(var a=y.B.Xj[a],j=a.length-1;0<=j;j--){var k=a[j];if((f||b==k.type)&&(h||c==k.capture))y.B.vz(k.key),e++}return e};y.B.dO=function(a,b,c){return y.B.KB(a,b,c)||[]};y.B.KB=function(a,b,c){var e=y.B.ng;return b in e&&(e=e[b],c in e&&(e=e[c],a=y.cm(a),e[a]))?e[a]:l};
y.B.cO=function(a,b,c,e,f){e=!!e;if(a=y.B.KB(a,b,e))for(b=0;b<a.length;b++)if(!a[b].Ko&&a[b].Iq==c&&a[b].capture==e&&a[b].ax==f)return a[b];return l};y.B.oO=function(a,b,c){var a=y.cm(a),e=y.B.Xj[a];if(e){var f=y.$n(b),h=y.$n(c);return f&&h?(e=y.B.ng[b],!!e&&!!e[c]&&a in e[c]):!f&&!h?i:y.O.some(e,function(a){return f&&a.type==b||h&&a.capture==c})}return n};y.B.SN=function(a){var b=[],c;for(c in a)a[c]&&a[c].id?b.push(c+" = "+a[c]+" ("+a[c].id+")"):b.push(c+" = "+a[c]);return b.join("\n")};
y.B.KG=function(a){return a in y.B.uD?y.B.uD[a]:y.B.uD[a]=y.B.iL+a};y.B.WN=function(a,b,c,e){var f=y.B.ng;return b in f&&(f=f[b],c in f)?y.B.Xp(f[c],a,b,c,e):i};y.B.Xp=function(a,b,c,e,f){var h=1,b=y.cm(b);if(a[b]){a.Sh--;a=a[b];a.Jx?a.Jx++:a.Jx=1;try{for(var j=a.length,k=0;k<j;k++){var m=a[k];m&&!m.Ko&&(h&=y.B.sB(m,f)!==n)}}finally{a.Jx--,y.B.vF(c,e,b,a)}}return Boolean(h)};y.B.sB=function(a,b){var c=a.handleEvent(b);a.uA&&y.B.vz(a.key);return c};y.B.jO=function(){return y.object.bm(y.B.Hd)};
y.B.dispatchEvent=function(a,b){var c=b.type||b,e=y.B.ng;if(!(c in e))return i;if(y.uc(b))b=new ha(b,a);else if(b instanceof ha)b.target=b.target||a;else{var f=b,b=new ha(c,a);y.object.extend(b,f)}var f=1,h,e=e[c],c=i in e,j;if(c){h=[];for(j=a;j;j=j.zD)h.push(j);j=e[i];j.Sh=j.fc;for(var k=h.length-1;!b.Io&&0<=k&&j.Sh;k--)b.currentTarget=h[k],f&=y.B.Xp(j,h[k],b.type,i,b)&&b.lu!=n}if(n in e)if(j=e[n],j.Sh=j.fc,c)for(k=0;!b.Io&&k<h.length&&j.Sh;k++)b.currentTarget=h[k],f&=y.B.Xp(j,h[k],b.type,n,b)&&
b.lu!=n;else for(e=a;!b.Io&&e&&j.Sh;e=e.zD)b.currentTarget=e,f&=y.B.Xp(j,e,b.type,n,b)&&b.lu!=n;return Boolean(f)};y.B.SO=function(a){y.B.gt=a.pI(y.B.gt)};
y.B.gt=function(a,b){if(!y.B.Hd[a])return i;var c=y.B.Hd[a],e=c.type,f=y.B.ng;if(!(e in f))return i;var f=f[e],h,j;if(!ea){h=b||y.AK();var k=i in f,m=n in f;if(k){if(y.B.QK(h))return i;y.B.$K(h)}var s=new ia;s.Un(h,this);h=i;try{if(k){for(var t=[],v=s.currentTarget;v;v=v.parentNode)t.push(v);j=f[i];j.Sh=j.fc;for(var x=t.length-1;!s.Io&&0<=x&&j.Sh;x--)s.currentTarget=t[x],h&=y.B.Xp(j,t[x],e,i,s);if(m){j=f[n];j.Sh=j.fc;for(x=0;!s.Io&&x<t.length&&j.Sh;x++)s.currentTarget=t[x],h&=y.B.Xp(j,t[x],e,n,s)}}else h=
y.B.sB(c,s)}finally{t&&(t.length=0),s.si()}return h}e=new ia(b,this);try{h=y.B.sB(c,e)}finally{e.si()}return h};y.B.$K=function(a){var b=n;if(0==a.keyCode)try{a.keyCode=-1;return}catch(c){b=i}if(b||a.returnValue==g)a.returnValue=i};y.B.QK=function(a){return 0>a.keyCode||a.returnValue!=g};y.B.ML=0;y.B.kO=function(a){return a+"_"+y.B.ML++};y.debug.we.vI(function(a){y.B.gt=a(y.B.gt)});function la(){}y.b(la,ga);w=la.prototype;w.PF=i;w.zD=l;w.addEventListener=function(a,b,c,e){y.B.hb(this,a,b,c,e)};w.removeEventListener=function(a,b,c,e){y.B.Lc(this,a,b,c,e)};w.dispatchEvent=function(a){return y.B.dispatchEvent(this,a)};w.Ol=function(){la.e.Ol.call(this);y.B.xI(this);this.zD=l};var ma=y.global.window;y.wt={};y.wt.SK=function(a){return/^\s*$/.test(a)?n:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};y.wt.parse=function(a){a=""+a;if(y.wt.SK(a))try{return eval("("+a+")")}catch(b){}d(Error("Invalid JSON string: "+a))};y.wt.sP=function(a){return eval("("+a+")")};y.wt.Ta=function(a,b){return(new na(b)).Ta(a)};
function na(a){this.uy=a}na.prototype.Ta=function(a){var b=[];oa(this,a,b);return b.join("")};
function oa(a,b,c){switch(typeof b){case "string":pa(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if(y.isArray(b)){var e=b.length;c.push("[");for(var f="",h=0;h<e;h++)c.push(f),f=b[h],oa(a,a.uy?a.uy.call(b,""+h,f):f,c),f=",";c.push("]");break}c.push("{");e="";for(h in b)Object.prototype.hasOwnProperty.call(b,h)&&(f=b[h],"function"!=typeof f&&(c.push(e),pa(h,c),
c.push(":"),oa(a,a.uy?a.uy.call(b,h,f):f,c),e=","));c.push("}");break;case "function":break;default:d(Error("Unknown type: "+typeof b))}}var qa={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},ra=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function pa(a,b){b.push('"',a.replace(ra,function(a){if(a in qa)return qa[a];var b=a.charCodeAt(0),f="\\u";16>b?f+="000":256>b?f+="00":4096>b&&(f+="0");return qa[a]=f+b.toString(16)}),'"')};y.Ci={};function sa(){}sa.prototype.pF=l;sa.prototype.at=function(){var a;if(!(a=this.pF))a={},ta(this)&&(a[0]=i,a[1]=i),a=this.pF=a;return a};function ua(a,b){this.XL=a;this.lL=b}y.b(ua,sa);ua.prototype.GA=function(){return this.XL()};ua.prototype.at=function(){return this.lL()};y.Ci.aj=function(){return y.Ci.aj.sG.GA()};y.Ci.aj.at=function(){return y.Ci.aj.sG.at()};y.Ci.aj.aP=function(a,b){y.Ci.aj.GI(new ua(a,b))};y.Ci.aj.GI=function(a){y.Ci.aj.sG=a};function va(){}y.b(va,sa);va.prototype.GA=function(){var a=ta(this);return a?new ActiveXObject(a):new XMLHttpRequest};va.prototype.lC=l;
function ta(a){if(!a.lC&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var e=b[c];try{return new ActiveXObject(e),a.lC=e}catch(f){}}d(Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed"))}return a.lC}y.Ci.aj.GI(new va);y.ad={};y.ad.bm=function(a){return"function"==typeof a.bm?a.bm():y.ze(a)||y.uc(a)?a.length:y.object.bm(a)};y.ad.ff=function(a){if("function"==typeof a.ff)return a.ff();if(y.uc(a))return a.split("");if(y.ze(a)){for(var b=[],c=a.length,e=0;e<c;e++)b.push(a[e]);return b}return y.object.ff(a)};y.ad.Lf=function(a){if("function"==typeof a.Lf)return a.Lf();if("function"!=typeof a.ff){if(y.ze(a)||y.uc(a)){for(var b=[],a=a.length,c=0;c<a;c++)b.push(c);return b}return y.object.Lf(a)}};
y.ad.contains=function(a,b){return"function"==typeof a.contains?a.contains(b):"function"==typeof a.Ip?a.Ip(b):y.ze(a)||y.uc(a)?y.O.contains(a,b):y.object.Ip(a,b)};y.ad.Hh=function(a){return"function"==typeof a.Hh?a.Hh():y.ze(a)||y.uc(a)?y.O.Hh(a):y.object.Hh(a)};y.ad.clear=function(a){"function"==typeof a.clear?a.clear():y.ze(a)?y.O.clear(a):y.object.clear(a)};
y.ad.forEach=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(y.ze(a)||y.uc(a))y.O.forEach(a,b,c);else for(var e=y.ad.Lf(a),f=y.ad.ff(a),h=f.length,j=0;j<h;j++)b.call(c,f[j],e&&e[j],a)};y.ad.filter=function(a,b,c){if("function"==typeof a.filter)return a.filter(b,c);if(y.ze(a)||y.uc(a))return y.O.filter(a,b,c);var e,f=y.ad.Lf(a),h=y.ad.ff(a),j=h.length;if(f){e={};for(var k=0;k<j;k++)b.call(c,h[k],f[k],a)&&(e[f[k]]=h[k])}else{e=[];for(k=0;k<j;k++)b.call(c,h[k],g,a)&&e.push(h[k])}return e};
y.ad.map=function(a,b,c){if("function"==typeof a.map)return a.map(b,c);if(y.ze(a)||y.uc(a))return y.O.map(a,b,c);var e,f=y.ad.Lf(a),h=y.ad.ff(a),j=h.length;if(f){e={};for(var k=0;k<j;k++)e[f[k]]=b.call(c,h[k],f[k],a)}else{e=[];for(k=0;k<j;k++)e[k]=b.call(c,h[k],g,a)}return e};y.ad.some=function(a,b,c){if("function"==typeof a.some)return a.some(b,c);if(y.ze(a)||y.uc(a))return y.O.some(a,b,c);for(var e=y.ad.Lf(a),f=y.ad.ff(a),h=f.length,j=0;j<h;j++)if(b.call(c,f[j],e&&e[j],a))return i;return n};
y.ad.every=function(a,b,c){if("function"==typeof a.every)return a.every(b,c);if(y.ze(a)||y.uc(a))return y.O.every(a,b,c);for(var e=y.ad.Lf(a),f=y.ad.ff(a),h=f.length,j=0;j<h;j++)if(!b.call(c,f[j],e&&e[j],a))return n;return i};y.$a={};y.$a.of="StopIteration"in y.global?y.global.StopIteration:Error("StopIteration");function wa(){}wa.prototype.next=function(){d(y.$a.of)};wa.prototype.Rz=function(){return this};y.$a.lh=function(a){if(a instanceof wa)return a;if("function"==typeof a.Rz)return a.Rz(n);if(y.ze(a)){var b=0,c=new wa;c.next=function(){for(;;){b>=a.length&&d(y.$a.of);if(b in a)return a[b++];b++}};return c}d(Error("Not implemented"))};
y.$a.forEach=function(a,b,c){if(y.ze(a))try{y.O.forEach(a,b,c)}catch(e){e!==y.$a.of&&d(e)}else{a=y.$a.lh(a);try{for(;;)b.call(c,a.next(),g,a)}catch(f){f!==y.$a.of&&d(f)}}};y.$a.filter=function(a,b,c){var a=y.$a.lh(a),e=new wa;e.next=function(){for(;;){var e=a.next();if(b.call(c,e,g,a))return e}};return e};
y.$a.VO=function(a,b,c){var e=0,f=a,h=c||1;1<arguments.length&&(e=a,f=b);0==h&&d(Error("Range step argument must not be zero"));var j=new wa;j.next=function(){(h>0&&e>=f||h<0&&e<=f)&&d(y.$a.of);var a=e;e=e+h;return a};return j};y.$a.join=function(a,b){return y.$a.JE(a).join(b)};y.$a.map=function(a,b,c){var a=y.$a.lh(a),e=new wa;e.next=function(){for(;;){var e=a.next();return b.call(c,e,g,a)}};return e};y.$a.reduce=function(a,b,c,e){var f=c;y.$a.forEach(a,function(a){f=b.call(e,f,a)});return f};
y.$a.some=function(a,b,c){a=y.$a.lh(a);try{for(;;)if(b.call(c,a.next(),g,a))return i}catch(e){e!==y.$a.of&&d(e)}return n};y.$a.every=function(a,b,c){a=y.$a.lh(a);try{for(;;)if(!b.call(c,a.next(),g,a))return n}catch(e){e!==y.$a.of&&d(e)}return i};y.$a.FN=function(a){var b=arguments,c=b.length,e=0,f=new wa;f.next=function(){try{return e>=c&&d(y.$a.of),y.$a.lh(b[e]).next()}catch(a){return(a!==y.$a.of||e>=c)&&d(a),e++,this.next()}};return f};
y.$a.PN=function(a,b,c){var a=y.$a.lh(a),e=new wa,f=i;e.next=function(){for(;;){var e=a.next();if(!f||!b.call(c,e,g,a))return f=n,e}};return e};y.$a.kP=function(a,b,c){var a=y.$a.lh(a),e=new wa,f=i;e.next=function(){for(;;)if(f){var e=a.next();if(b.call(c,e,g,a))return e;f=n}else d(y.$a.of)};return e};y.$a.JE=function(a){if(y.ze(a))return y.O.JE(a);var a=y.$a.lh(a),b=[];y.$a.forEach(a,function(a){b.push(a)});return b};
y.$a.kB=function(a,b){var a=y.$a.lh(a),b=y.$a.lh(b),c,e;try{for(;;){c=e=n;var f=a.next();c=i;var h=b.next();e=i;if(f!=h)break}}catch(j){j!==y.$a.of&&d(j);if(c&&!e)return n;if(!e)try{b.next()}catch(k){return k!==y.$a.of&&d(k),i}}return n};y.$a.LO=function(a,b){try{return y.$a.lh(a).next()}catch(c){return c!=y.$a.of&&d(c),b}};
y.$a.product=function(a){if(y.O.some(arguments,function(a){return!a.length})||!arguments.length)return new wa;var b=new wa,c=arguments,e=y.O.repeat(0,c.length);b.next=function(){if(e){for(var a=y.O.map(e,function(a,b){return c[b][a]}),b=e.length-1;0<=b;b--){if(e[b]<c[b].length-1){e[b]++;break}if(0==b){e=l;break}e[b]=0}return a}d(y.$a.of)};return b};
y.$a.NN=function(a){var b=y.$a.lh(a),c=[],e=0,a=new wa,f=n;a.next=function(){var a=l;if(!f)try{return a=b.next(),c.push(a),a}catch(j){(j!=y.$a.of||y.O.Hh(c))&&d(j),f=i}a=c[e];e=(e+1)%c.length;return a};return a};function xa(a,b){this.pg={};this.Xa=[];var c=arguments.length;if(1<c){c%2&&d(Error("Uneven number of arguments"));for(var e=0;e<c;e+=2)this.set(arguments[e],arguments[e+1])}else if(a){a instanceof xa?(c=a.Lf(),e=a.ff()):(c=y.object.Lf(a),e=y.object.ff(a));for(var f=0;f<c.length;f++)this.set(c[f],e[f])}}w=xa.prototype;w.fc=0;w.$u=0;w.bm=q("fc");w.ff=function(){ya(this);for(var a=[],b=0;b<this.Xa.length;b++)a.push(this.pg[this.Xa[b]]);return a};w.Lf=function(){ya(this);return this.Xa.concat()};
w.nj=function(a){return za(this.pg,a)};w.Ip=function(a){for(var b=0;b<this.Xa.length;b++){var c=this.Xa[b];if(za(this.pg,c)&&this.pg[c]==a)return i}return n};w.kB=function(a,b){if(this===a)return i;if(this.fc!=a.bm())return n;var c=b||Aa;ya(this);for(var e,f=0;e=this.Xa[f];f++)if(!c(this.get(e),a.get(e)))return n;return i};function Aa(a,b){return a===b}w.Hh=function(){return 0==this.fc};w.clear=function(){this.pg={};this.$u=this.fc=this.Xa.length=0};
w.remove=function(a){return za(this.pg,a)?(delete this.pg[a],this.fc--,this.$u++,this.Xa.length>2*this.fc&&ya(this),i):n};function ya(a){if(a.fc!=a.Xa.length){for(var b=0,c=0;b<a.Xa.length;){var e=a.Xa[b];za(a.pg,e)&&(a.Xa[c++]=e);b++}a.Xa.length=c}if(a.fc!=a.Xa.length){for(var f={},c=b=0;b<a.Xa.length;)e=a.Xa[b],za(f,e)||(a.Xa[c++]=e,f[e]=1),b++;a.Xa.length=c}}w.get=function(a,b){return za(this.pg,a)?this.pg[a]:b};
w.set=function(a,b){za(this.pg,a)||(this.fc++,this.Xa.push(a),this.$u++);this.pg[a]=b};w.pa=function(){return new xa(this)};w.IL=function(){for(var a=new xa,b=0;b<this.Xa.length;b++){var c=this.Xa[b];a.set(this.pg[c],c)}return a};w.Rz=function(a){ya(this);var b=0,c=this.Xa,e=this.pg,f=this.$u,h=this,j=new wa;j.next=function(){for(;;){f!=h.$u&&d(Error("The map has changed since the iterator was created"));b>=c.length&&d(y.$a.of);var j=c[b++];return a?j:e[j]}};return j};
function za(a,b){return Object.prototype.hasOwnProperty.call(a,b)};y.uri={};y.uri.G={};y.uri.G.mF=function(a,b,c,e,f,h,j){var k=[];a&&k.push(a,":");c&&(k.push("//"),b&&k.push(b,"@"),k.push(c),e&&k.push(":",e));f&&k.push(f);h&&k.push("?",h);j&&k.push("#",j);return k.join("")};y.uri.G.DL=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");y.uri.G.split=function(a){return a.match(y.uri.G.DL)};y.uri.G.kw=function(a){return a&&decodeURIComponent(a)};
y.uri.G.eq=function(a,b){return y.uri.G.split(b)[a]||l};y.uri.G.TB=function(a){return y.uri.G.eq(1,a)};y.uri.G.vK=function(a){a=y.uri.G.TB(a);!a&&self.location&&(a=self.location.protocol,a=a.substr(0,a.length-1));return a?a.toLowerCase():""};y.uri.G.EK=function(a){return y.uri.G.eq(2,a)};y.uri.G.UG=function(a){return y.uri.G.kw(y.uri.G.EK(a))};y.uri.G.uK=function(a){return y.uri.G.eq(3,a)};y.uri.G.DG=function(a){return y.uri.G.kw(y.uri.G.uK(a))};
y.uri.G.PB=function(a){return Number(y.uri.G.eq(4,a))||l};y.uri.G.CK=function(a){return y.uri.G.eq(5,a)};y.uri.G.bt=function(a){return y.uri.G.kw(y.uri.G.CK(a))};y.uri.G.MG=function(a){return y.uri.G.eq(6,a)};y.uri.G.xK=function(a){var b=a.indexOf("#");return 0>b?l:a.substr(b+1)};y.uri.G.bP=function(a,b){return y.uri.G.sL(a)+(b?"#"+b:"")};y.uri.G.FG=function(a){return y.uri.G.kw(y.uri.G.xK(a))};y.uri.G.aO=function(a){a=y.uri.G.split(a);return y.uri.G.mF(a[1],a[2],a[3],a[4])};
y.uri.G.iO=function(a){a=y.uri.G.split(a);return y.uri.G.mF(l,l,l,l,a[5],a[6],a[7])};y.uri.G.sL=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};y.uri.G.rO=function(a,b){var c=y.uri.G.split(a),e=y.uri.G.split(b);return c[3]==e[3]&&c[1]==e[1]&&c[4]==e[4]};y.uri.G.yJ=function(a){y.Oz&&(0<=a.indexOf("#")||0<=a.indexOf("?"))&&d(Error("goog.uri.utils: Fragment or query identifiers are not supported: ["+a+"]"))};
y.uri.G.Uz=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=g)}return a.join("")};y.uri.G.iF=function(a,b,c){if(y.isArray(b))for(var e=0;e<b.length;e++)c.push("&",a),""!==b[e]&&c.push("=",y.J.Ar(b[e]));else b!=l&&(c.push("&",a),""!==b&&c.push("=",y.J.Ar(b)))};y.uri.G.kA=function(a,b,c){for(c=c||0;c<b.length;c+=2)y.uri.G.iF(b[c],b[c+1],a);return a};
y.uri.G.AN=function(a,b){var c=y.uri.G.kA([],a,b);c[0]="";return c.join("")};y.uri.G.nF=function(a,b){for(var c in b)y.uri.G.iF(c,b[c],a);return a};y.uri.G.BN=function(a){a=y.uri.G.nF([],a);a[0]="";return a.join("")};y.uri.G.kN=function(a,b){return y.uri.G.Uz(2==arguments.length?y.uri.G.kA([a],arguments[1],0):y.uri.G.kA([a],arguments,1))};y.uri.G.lN=function(a,b){return y.uri.G.Uz(y.uri.G.nF([a],b))};y.uri.G.xJ=function(a,b){return y.uri.G.Uz([a,"&","zx","=",y.J.Ar(b)])};
y.uri.G.Aw=function(a,b,c,e){for(var f=c.length;0<=(b=a.indexOf(c,b))&&b<e;){var h=a.charCodeAt(b-1);if(38==h||63==h)if(h=a.charCodeAt(b+f),!h||61==h||38==h||35==h)return b;b+=f+1}return-1};y.uri.G.bx=/#|$/;y.uri.G.pO=function(a,b){return 0<=y.uri.G.Aw(a,0,b,a.search(y.uri.G.bx))};y.uri.G.gO=function(a,b){var c=a.search(y.uri.G.bx),e=y.uri.G.Aw(a,0,b,c);if(0>e)return l;var f=a.indexOf("&",e);if(0>f||f>c)f=c;e+=b.length+1;return y.J.yz(a.substr(e,f-e))};
y.uri.G.hO=function(a,b){for(var c=a.search(y.uri.G.bx),e=0,f,h=[];0<=(f=y.uri.G.Aw(a,e,b,c));){e=a.indexOf("&",f);if(0>e||e>c)e=c;f+=b.length+1;h.push(y.J.yz(a.substr(f,e-f)))}return h};y.uri.G.HL=/[?&]($|#)/;y.uri.G.tL=function(a){for(var b=a.search(y.uri.G.bx),c=0,e,f=[];0<=(e=y.uri.G.Aw(a,c,"zx",b));)f.push(a.substring(c,e)),c=Math.min(a.indexOf("&",e)+1||b,b);f.push(a.substr(c));return f.join("").replace(y.uri.G.HL,"$1")};
y.uri.G.BL=function(a){var b=y.J.NG();return y.uri.G.xJ(y.uri.G.tL(a),b)};y.uri.G.mN=function(a,b){y.uri.G.yJ(a);y.J.hK(a)&&(a=a.substr(0,a.length-1));y.J.EL(b)&&(b=b.substr(1));return y.J.BJ(a,"/",b)};y.uri.G.ZK=function(a){return y.uri.G.BL(a)};function Ba(a){la.call(this);this.headers=new xa;this.Jz=a||l}y.b(Ba,la);Ba.dF="Content-Type";Ba.rJ=/^https?$/i;Ba.oJ="application/x-www-form-urlencoded;charset=utf-8";Ba.SD=[];Ba.send=function(a,b,c,e,f,h){var j=new Ba;Ba.SD.push(j);b&&y.B.hb(j,"complete",b);y.B.hb(j,"ready",y.kI(Ba.DJ,j));h&&(j.IE=Math.max(0,h));j.send(a,c,e,f)};Ba.GN=function(){for(var a=Ba.SD;a.length;)a.pop().si()};Ba.TO=function(a){Ba.prototype.Ut=a.pI(Ba.prototype.Ut)};Ba.DJ=function(a){a.si();y.O.remove(Ba.SD,a)};w=Ba.prototype;
w.ul=n;w.hc=l;w.Iz=l;w.IH="";w.lB=n;w.fx=n;w.mC=n;w.Tn=n;w.IE=0;w.bp=l;w.AI="";w.TE=n;
w.send=function(a,b,c,e){this.hc&&d(Error("[goog.net.XhrIo] Object is active with another request"));b=b?b.toUpperCase():"GET";this.IH=a;this.lB=n;this.ul=i;this.hc=this.Jz?this.Jz.GA():y.Ci.aj();this.Iz=this.Jz?this.Jz.at():y.Ci.aj.at();this.hc.onreadystatechange=y.bind(this.jI,this);try{this.mC=i,this.hc.open(b,a,i),this.mC=n}catch(f){Ca(this);return}var a=c||"",h=this.headers.pa();e&&y.ad.forEach(e,function(a,b){h.set(b,a)});"POST"==b&&!h.nj(Ba.dF)&&h.set(Ba.dF,Ba.oJ);y.ad.forEach(h,function(a,
b){this.hc.setRequestHeader(b,a)},this);this.AI&&(this.hc.responseType=this.AI);y.object.nj(this.hc,"withCredentials")&&(this.hc.withCredentials=this.TE);try{this.bp&&(ma.clearTimeout(this.bp),this.bp=l),0<this.IE&&(this.bp=ma.setTimeout(y.bind(this.GL,this),this.IE)),this.fx=i,this.hc.send(a),this.fx=n}catch(j){Ca(this)}};w.GL=function(){"undefined"!=typeof y&&this.hc&&(this.dispatchEvent("timeout"),this.abort(8))};function Ca(a){a.ul=n;a.hc&&(a.Tn=i,a.hc.abort(),a.Tn=n);Da(a);Ea(a)}
function Da(a){a.lB||(a.lB=i,a.dispatchEvent("complete"),a.dispatchEvent("error"))}w.abort=function(){this.hc&&this.ul&&(this.ul=n,this.Tn=i,this.hc.abort(),this.Tn=n,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Ea(this))};w.Ol=function(){this.hc&&(this.ul&&(this.ul=n,this.Tn=i,this.hc.abort(),this.Tn=n),Ea(this,i));Ba.e.Ol.call(this)};w.jI=function(){!this.mC&&!this.fx&&!this.Tn?this.Ut():Fa(this)};w.Ut=function(){Fa(this)};
function Fa(a){if(a.ul&&"undefined"!=typeof y&&(!a.Iz[1]||!(4==(a.hc?a.hc.readyState:0)&&2==Ga(a))))if(a.fx&&4==(a.hc?a.hc.readyState:0))ma.setTimeout(y.bind(a.jI,a),0);else if(a.dispatchEvent("readystatechange"),4==(a.hc?a.hc.readyState:0)){a.ul=n;var b=Ga(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 304:case 1223:c=i;break a;default:c=n}if(!c){if(b=0===b)b=y.uri.G.vK(""+a.IH),b=!Ba.rJ.test(b);c=b}c?(a.dispatchEvent("complete"),a.dispatchEvent("success")):Da(a);Ea(a)}}
function Ea(a,b){if(a.hc){var c=a.hc,e=a.Iz[0]?y.bI:l;a.hc=l;a.Iz=l;a.bp&&(ma.clearTimeout(a.bp),a.bp=l);b||a.dispatchEvent("ready");try{c.onreadystatechange=e}catch(f){}}}function Ga(a){try{return 2<(a.hc?a.hc.readyState:0)?a.hc.status:-1}catch(b){return-1}}y.debug.we.vI(function(a){Ba.prototype.Ut=a(Ba.prototype.Ut)});function Ha(a){a=typeof a;return"string"==a||"number"==a||"boolean"==a}function Ia(a){return"string"!=typeof a&&"undefined"!=typeof a.length}
function Ja(a,b){var c="<"+a;"undefined"!=typeof b.functionName&&(b["function"]=b.functionName,delete b.functionName);for(var e in b)"format"!=e&&"text"!=e&&"custom_attribute_value"!=e&&"attr"!=e&&Ha(b[e])&&(c+=" "+e+'="'+b[e]+'"');c+=">";for(e in b)if("arg"==e&&Ia(b[e]))for(var f=b[e],h=0;h<f.length;h++)c+="<arg><![CDATA["+f[h]+"]]\></arg>";else if("custom_attribute_value"==e||"attr"==e)c+="<![CDATA["+b[e]+"]]\>";else if("format"==e||"text"==e)c+="<"+e+"><![CDATA["+b[e]+"]]\></"+e+">";else if(Ia(b[e])){f=
b[e];for(h=0;h<f.length;h++)c+=Ja(e,f[h])}else Ha(b[e])||(c+=Ja(e,b[e]));return c+("</"+a+">")}function Ka(){}w=Ka.prototype;w.ca=l;w.q=l;w.Xl=l;w.ay=l;w.$x=l;w.ZH=l;w.nD=l;w.zw=l;w.Un=function(a){this.ca=a;this.nD=this.ZH=this.$x=this.ay=this.Ik=n;this.sh=this.ca.enableFirefoxPrintPreviewFix};w.Ik=n;w.eI=function(){this.Ik=i;this.ay&&this.Yh(this.ca.xmlFile);this.$x&&this.ih(this.ca.xmlData);this.ZH&&this.Rm(this.ca.jsonFile);this.nD&&this.Oi(this.ca.jsonData)};w.fI=function(){this.sh&&La(this)};
w.yc=u(l);w.jt=function(){this.ca.visible=n;this.q&&(this.q.style.visibility="hidden",this.q.setAttribute("width","1px"),this.q.setAttribute("height","1px"))};w.show=function(){this.ca.visible=i;this.q&&(this.q.style.visibility="visible",this.q.setAttribute("width",this.La+""),this.q.setAttribute("height",this.Wa+""))};
w.Pp=function(a,b){a&&"OBJECT"==a.nodeName&&(A.platform.zq&&A.platform.ho?(a.style.display="none",function(){4==a.readyState?(A.platform.Mj&&b!=l&&A.Hs(window[b]),A.Hs(a)):setTimeout(arguments.callee,10)}()):a.parentNode.removeChild(a))};w.Hs=function(a){for(var b in a)"function"==typeof a[b]&&(a[b]=l);a.parentNode&&a.parentNode.removeChild(a)};w.sn=function(){return A.platform.hC&&this.ca.swfFile!=l};
w.write=function(a){var b=this.ca.width+"",c=this.ca.height+"",e=this.ca.preloaderSWFFile?this.ca.preloaderSWFFile:this.ca.swfFile;if(this.sh=this.sh&&A.platform.mH)this.zw=new Ma;if(A.platform.zq&&A.platform.ho){var f;f='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+(' id="'+this.ca.id+'"');f=f+(' width="'+b+'"')+(' height="'+c+'"')+(' style="visibility:'+(this.ca.visible?"visible":"hidden")+'"');f+=' codebase="'+A.platform.protocol+'//fpdownload.macromedia.com/get/flashplayer/current/swflash.cab">';
f+=Na("movie",e);f+=Na("bgcolor",this.ca.bgColor);f+=Na("allowScriptAccess","always");f+=Na("flashvars",Oa(this));this.ca.wMode!=l&&(f+=Na("wmode",this.ca.wMode));f+="</object>";if(A.platform.Mj){b=l;for(c=a;c;){if(c.nodeName!=l&&"form"==c.nodeName.toLowerCase()){b=c;break}c=c.parentNode}if(b!=l){window[this.ca.id]={};window[this.ca.id].sJ=o();a.innerHTML=f;window[this.ca.id].sJ=l;var a={},h;for(h in window[this.ca.id])"function"==typeof window[this.ca.id][h]&&(a[h]=window[this.ca.id][h]);this.q=
window[this.ca.id]=b[this.ca.id];this.ca.flashObject=this.q;for(h in a)Pa(h)}else a.innerHTML=f,this.q=document.getElementById(this.ca.id),this.ca.flashObject=this.q}else a.innerHTML=f,this.q=document.getElementById(this.ca.id),this.ca.flashObject=this.q}else{h=document.createElement("object");h.setAttribute("type","application/x-shockwave-flash");h.setAttribute("id",this.ca.id);h.setAttribute("width",b);h.setAttribute("height",c);h.setAttribute("data",e);h.setAttribute("style","visibility: "+(this.ca.visible?
"visible":"hidden"));Qa(h,"movie",e);Qa(h,"bgcolor",this.ca.bgColor);Qa(h,"allowScriptAccess","always");Qa(h,"flashvars",Oa(this));this.ca.wMode!=l&&Qa(h,"wmode",this.ca.wMode);if(a.hasChildNodes())for(;0<a.childNodes.length;)a.removeChild(a.firstChild);this.q=a.appendChild(h);this.ca.flashObject=this.q;this.Xl=a}return this.q!=l};function Na(a,b){return'<param name="'+a+'" value="'+b+'" />'}
function Qa(a,b,c){var e=document.createElement("param");e.setAttribute("name",b);e.setAttribute("value",c);a.appendChild(e)}function Pa(a){eval('obj[functionName] = function(){return eval(this.CallFunction("<invoke name=\\"'+a+'\\" returntype=\\"javascript\\">" + __flash__argumentsToXML(arguments,0) + "</invoke>"));}')}
function Oa(a){var b="__externalobjid="+a.ca.id;a.ca.preloaderSWFFile&&(b+="&swffile="+a.ca.swfFile);a.ca.xmlFile&&(b+="&xmlfile="+a.ca.xmlFile);a.ca.enabledChartEvents&&(b+="&__enableevents=1");a.ca.enabledChartMouseEvents&&(b+="&__enablechartmouseevents=1");b+="&preloaderInit="+a.ca.messages.preloaderInit;b+="&preloaderLoading="+a.ca.messages.preloaderLoading;b+="&init="+a.ca.messages.init;b+="&loadingConfig="+a.ca.messages.loadingConfig;b+="&loadingTemplates="+a.ca.messages.loadingTemplates;b+=
"&loadingResources="+a.ca.messages.loadingResources;b+="&noData="+a.ca.messages.noData;return b+="&waitingForData="+a.ca.messages.waitingForData}w.bs=u(i);w.xz=function(){(this.sh||this.Xl)&&this.zw.si();La(this)};w.Uo=function(a,b){this.q&&(this.q.setAttribute("width",a+""),this.q.setAttribute("height",b+""))};
w.remove=function(){this.q&&(this.q.Dispose&&this.q.Dispose(),Ra(this.q,this.im),this.sh&&(this.sh||this.Xl)&&this.zw.si());this.q=l;this.ca.flashObject=this.q;if(A&&A.GK())for(var a=A.JG(),b=0;b<a;b++)if(A.BG()[b]==this){A.BG().splice(b,1);break}A&&A.CG()&&this.im!=l&&(A.CG()[this.im]=l)};w.clear=function(){this.q&&this.q.Clear&&this.q.Clear()};w.refresh=function(){this.q!=l&&this.q.Refresh!=l&&this.q.Refresh()};w.xr=function(a,b){this.q!=l&&this.q.UpdateData!=l&&this.q.UpdateData(a,b)};
w.Ny=function(a){this.q&&this.q.SetLoading&&this.q.SetLoading(a)};w.Fw=function(){return this.q.GetInformation()};w.Yh=function(a){this.q&&this.Ik?this.q.SetXMLDataFromURL(a):this.ay=i};w.ih=function(a){this.q&&this.Ik?this.q.SetXMLDataFromString(a):this.$x=i};w.Rm=o();w.Oi=function(a){this.q&&this.Ik?this.ih(Ja("anychart",a)):this.nD=i};w.xu=function(a){this.q&&this.Ik?this.q.SetXMLDataFromString(a):this.$x=i};w.Vy=function(a){this.q&&this.Ik?this.q.SetXMLDataFromURL(a):this.ay=i};
w.Vo=function(a,b){this.q&&this.Ik&&this.q.UpdateViewFromURL(a,b)};w.Ry=function(a,b){this.q&&this.Ik&&this.q.UpdateViewFromString(a,b)};w.rd=function(a,b){this.q!=l&&this.q.AddPoint!=l&&this.q.AddPoint(a,b)};w.bj=function(a,b,c){this.q!=l&&this.q.AddPointAt!=l&&this.q.AddPointAt(a,b,c)};w.Rj=function(a,b){this.q!=l&&this.q.RemovePoint!=l&&this.q.RemovePoint(a,b)};w.ak=function(a,b,c){this.q!=l&&this.q.UpdatePoint!=l&&this.q.UpdatePoint(a,b,c)};
w.bk=function(a,b,c){this.q!=l&&this.q.UpdatePointData!=l&&this.q.UpdatePointData(a,b,c)};w.Cj=function(a,b,c){this.q!=l&&this.q.HighlightPoint!=l&&this.q.HighlightPoint(a,b,c)};w.Ki=function(a,b,c){this.q!=l&&this.q.SelectPoint!=l&&this.q.SelectPoint(a,b,c)};w.wz=function(a,b,c,e){this.q&&this.q.updatePointWithAnimation!=l&&this.q.updatePointWithAnimation(a,b,c,e)};w.fz=function(){this.q&&this.q.startPointsUpdate!=l&&this.q.startPointsUpdate()};w.cj=function(a){this.q!=l&&this.q.AddSeries!=l&&this.q.AddSeries(a)};
w.dj=function(a,b){this.q!=l&&this.q.AddSeriesAt!=l&&this.q.AddSeriesAt(a,b)};w.Sj=function(a){this.q!=l&&this.q.RemoveSeries!=l&&this.q.RemoveSeries(a)};w.ck=function(a,b){this.q!=l&&this.q.UpdateSeries!=l&&this.q.UpdateSeries(a,b)};w.Wj=function(a,b){this.q!=l&&this.q.ShowSeries!=l&&this.q.ShowSeries(a,b)};w.Dj=function(a,b){this.q!=l&&this.q.HighlightSeries!=l&&this.q.HighlightSeries(a,b)};w.Bj=function(a,b){this.q!=l&&this.q.HighlightCategory!=l&&this.q.HighlightCategory(a,b)};
w.bz=function(a,b){this.q!=l&&this.q.ShowAxisMarker!=l&&this.q.ShowAxisMarker(a,b)};w.Vj=function(a,b){this.q!=l&&this.q.SetPlotCustomAttribute!=l&&this.q.SetPlotCustomAttribute(a,b)};w.Or=function(a,b,c){this.q!=l&&this.q.View_SetPlotCustomAttribute!=l&&this.q.View_SetPlotCustomAttribute(a,b,c)};w.Fr=function(a,b){this.q!=l&&this.q.View_AddSeries!=l&&this.q.View_AddSeries(a,b)};w.Mr=function(a,b){this.q!=l&&this.q.View_RemoveSeries!=l&&this.q.View_RemoveSeries(a,b)};
w.Gr=function(a,b,c){this.q!=l&&this.q.View_AddSeriesAt!=l&&this.q.View_AddSeriesAt(a,b,c)};w.Rr=function(a,b,c){this.q!=l&&this.q.View_UpdateSeries!=l&&this.q.View_UpdateSeries(a,b,c)};w.Pr=function(a,b,c){this.q!=l&&this.q.View_ShowSeries!=l&&this.q.View_ShowSeries(a,b,c)};w.Dr=function(a,b,c){this.q!=l&&this.q.View_AddPoint!=l&&this.q.View_AddPoint(a,b,c)};w.Er=function(a,b,c,e){this.q!=l&&this.q.View_AddPointAt!=l&&this.q.View_AddPointAt(a,b,c,e)};
w.Lr=function(a,b,c){this.q!=l&&this.q.View_RemovePoint!=l&&this.q.View_RemovePoint(a,b,c)};w.Qr=function(a,b,c,e){this.q!=l&&this.q.View_UpdatePoint!=l&&this.q.View_UpdatePoint(a,b,c,e)};w.Fz=function(a){this.q!=l&&this.q.View_Clear!=l&&this.q.View_Clear(a)};w.Kr=function(a){this.q!=l&&this.q.View_Refresh!=l&&this.q.View_Refresh(a)};w.Jr=function(a,b,c){this.q!=l&&this.q.View_HighlightSeries!=l&&this.q.View_HighlightSeries(a,b,c)};
w.Ir=function(a,b,c,e){this.q!=l&&this.q.View_HighlightPoint!=l&&this.q.View_HighlightPoint(a,b,c,e)};w.Hr=function(a,b,c){this.q!=l&&this.q.View_HighlightCategory!=l&&this.q.View_HighlightCategory(a,b,c)};w.Nr=function(a,b,c,e){this.q!=l&&this.q.View_SelectPoint!=l&&this.q.View_SelectPoint(a,b,c,e)};w.yr=function(a,b,c,e){this.q!=l&&this.q.UpdateViewPointData!=l&&this.q.UpdateViewPointData(b,c,e)};w.jq=function(a,b){return this.q.GetPngScreen(a,b)};
w.Sw=function(a,b){return this.q.GetPdfScreen(a,b)};w.ry=function(){this.q.PrintChart()};w.Fy=function(a,b){this.q.SaveAsImage(a,b)};w.Gy=function(a,b){this.q.SaveAsPDF(a,b)};w.Hy=function(a){this.q!=l&&this.q.ScrollXTo!=l&&this.q.ScrollXTo(a)};w.Iy=function(a){this.q!=l&&this.q.ScrollYTo!=l&&this.q.ScrollYTo(a)};w.scrollTo=function(a,b){this.q!=l&&this.q.ScrollTo!=l&&this.q.ScrollTo(a,b)};w.Cz=function(a,b){this.q!=l&&this.q.ViewScrollXTo!=l&&this.q.ViewScrollXTo(a,b)};
w.Dz=function(a,b){this.q!=l&&this.q.ViewScrollYTo!=l&&this.q.ViewScrollYTo(a,b)};w.Xw=function(){return this.q!=l&&this.q.GetXScrollInfo!=l?this.q.GetXScrollInfo():l};w.Yw=function(){return this.q!=l&&this.q.GetYScrollInfo!=l?this.q.GetYScrollInfo():l};w.Vw=function(a){if(this.q!=l&&this.q.GetViewXScrollInfo!=l)return this.q.GetViewXScrollInfo(a)};w.Ww=function(a){if(this.q!=l&&this.q.GetViewYScrollInfo!=l)return this.q.GetViewYScrollInfo(a)};w.Wy=function(a){this.q!=l&&this.q.SetXZoom!=l&&this.q.SetXZoom(a)};
w.Xy=function(a){this.q!=l&&this.q.SetYZoom!=l&&this.q.SetYZoom(a)};w.Yy=function(a,b){this.q!=l&&this.q.SetZoom!=l&&this.q.SetZoom(a,b)};w.Sy=function(a,b){this.q!=l&&this.q.SetViewXZoom!=l&&this.q.SetViewXZoom(a,b)};w.Ty=function(a,b){this.q!=l&&this.q.SetViewYZoom!=l&&this.q.SetViewYZoom(a,b)};w.Uy=function(a,b,c){this.q!=l&&this.q.SetViewZoom!=l&&this.q.SetViewZoom(a,b,c)};w.rv=function(){this.q!=l&&this.q.RepeatAnimation!=l&&this.q.RepeatAnimation()};
function Ra(a,b){a&&"OBJECT"==a.nodeName&&(A.platform.zq&&A.platform.ho?(a.style.display="none",function(){4==a.readyState?(A.platform.Mj&&b&&this.Hs(window[b]),A.Hs(a)):setTimeout(arguments.callee,10)}()):a.parentNode.removeChild(a))}w.Hs=function(a){for(var b in a)"function"==typeof a[b]&&(a[b]=l);a.parentNode&&a.parentNode.removeChild(a)};
function La(a){if(a.sh&&a.Xl){var b=a.jq();if(b&&0!=b.length){var c=a.Xl.getAttribute("id");c||(c="__chart_generated_container__"+a.im,a.Xl.setAttribute("id",c));var e=a.zw,f=a.Xl,h=a.La+"",j=a.Wa+"",a=a.Xl.nodeName,k=document.getElementsByTagName("head");if(k=0<k.length?k[0]:l){var m;m=k;var s=document.createElement("style");s.setAttribute("type","text/css");s.setAttribute("media","screen");var t=a+"#"+c,v=t+" img";s.appendChild(document.createTextNode(t+(" object { width:"+h+"; height:"+j+";padding:0; margin:0; }\n")));
s.appendChild(document.createTextNode(v+" { display: none; }"));m=m.appendChild(s);e.Ns=m;m=document.createElement("style");m.setAttribute("type","text/css");m.setAttribute("media","print");a=a+"#"+c;c=a+" img";h=" { display: block; width: "+h+"; height: "+j+"; }";m.appendChild(document.createTextNode(a+" object { display: none; }\n"));m.appendChild(document.createTextNode(c+h));h=k.appendChild(m);e.Os=h;h=document.createElement("img");h=f.appendChild(h);h.src="data:image/png;base64,"+b;e.Ms=h}}}}
function Ma(){}w.Ns=l;w.Os=l;w.Ms=l;Ma.prototype.si=function(){this.Ms&&this.Ms.parentNode&&this.Ms.parentNode.removeChild(this.Ms);this.Ns&&(this.Ns.parentNode.removeChild(this.Ns),this.Ns=l);this.Os&&(this.Os.parentNode.removeChild(this.Os),this.Os=l)};y.eg("anychart.scope.goog",y);y.eg("anychart.scope.Event",ha);y.eg("anychart.scope.EventTarget",la);y.eg("anychart.scope.EventType",z);y.eg("anychart.scope.XhrIo",Ba);var Sa={};y.eg("anychart.WMode",Sa);y.K(Sa,"WINDOW","window");y.K(Sa,"TRANSPARENT","transparent");y.K(Sa,"OPAQUE","opaque");var Ta={};y.eg("anychart.RenderingType",Ta);y.K(Ta,"FLASH_ONLY","flash");y.K(Ta,"SVG_ONLY","svg");y.K(Ta,"FLASH_PREFERRED","flashPreferred");y.K(Ta,"SVG_PREFERRED","svgPreferred");
function A(a,b,c){c&&(this.id=c);this.swfFile=A.swfFile;this.preloaderSWFFile=A.preloaderSWFFile;this.width=A.width;this.height=A.height;this.enableFirefoxPrintPreviewFix=A.enableFirefoxPrintPreviewFix;this.enabledChartEvents=A.enabledChartEvents;this.enabledChartMouseEvents=A.enabledChartMouseEvents;this.renderingType=A.renderingType;this.watermark=A.watermark;this.messages.preloaderInit=A.messages.preloaderInit;this.messages.preloaderLoading=A.messages.preloaderLoading;this.messages.init=A.messages.init;
this.messages.loadingConfig=A.messages.loadingConfig;this.messages.loadingResources=A.messages.loadingResources;this.messages.loadingTemplates=A.messages.loadingTemplates;this.messages.noData=A.messages.noData;this.messages.waitingForData=A.messages.waitingForData;a&&(this.swfFile=a);b&&(this.preloaderSWFFile=b);this.Hd={};A.rL(this)}y.eg("AnyChart",A);A.VERSION="6.0.10 (build #36916)";y.K(A,"VERSION",A.VERSION);A.width=550;y.K(A,"width",A.width);A.height=400;y.K(A,"height",A.height);A.ND="flash";
y.K(A,"renderingType",A.ND);A.fB=i;y.K(A,"enabledChartEvents",A.fB);A.gB=n;y.K(A,"enabledChartMouseEvents",A.gB);A.GE=l;y.K(A,"swfFile",A.GE);A.KD=l;y.K(A,"preloaderSWFFile",A.KD);A.sh=i;y.K(A,"enableFirefoxPrintPreviewFix",A.sh);A.prototype.id=l;y.K(A.prototype,"id",A.prototype.id);A.gs=[];A.GK=function(){return A.gs&&0<A.JG()};A.JG=function(){return A.gs.length};A.BG=function(){return A.gs};A.Dp={};A.CG=function(){return A.Dp};A.prototype.ND=l;y.K(A.prototype,"renderingType",A.prototype.ND);
A.prototype.ia=l;A.prototype.Hj=n;A.prototype.ZL=l;y.K(A.prototype,"xmlFile",A.prototype.ZL);A.prototype.UK=l;y.K(A.prototype,"jsonFile",A.prototype.UK);A.prototype.YL=l;y.K(A.prototype,"xmlData",A.prototype.YL);A.prototype.TK=l;y.K(A.prototype,"jsonData",A.prototype.TK);A.prototype.width=l;y.K(A.prototype,"width",A.prototype.width);A.prototype.height=l;y.K(A.prototype,"height",A.prototype.height);A.prototype.VL=l;y.K(A.prototype,"watermark",A.prototype.VL);A.prototype.GE=l;
y.K(A.prototype,"swfFile",A.prototype.GE);A.prototype.KD=l;y.K(A.prototype,"preloaderSWFFile",A.prototype.KD);A.prototype.sh=i;y.K(A.prototype,"enableFirefoxPrintPreviewFix",A.prototype.sh);A.prototype.UL=l;y.K(A.prototype,"wMode",A.prototype.UL);A.prototype.fB=i;y.K(A.prototype,"enabledChartEvents",A.prototype.fB);A.prototype.gB=n;y.K(A.prototype,"enabledChartMouseEvents",A.prototype.gB);A.prototype.Hd=l;A.prototype.bgColor="#FFFFFF";y.K(A.prototype,"bgColor",A.prototype.bgColor);
A.prototype.TL=i;y.K(A.prototype,"visible",A.prototype.TL);A.prototype.show=function(){this.visible=i;this.ia.show()};y.K(A.prototype,"show",A.prototype.show);A.prototype.jt=function(){this.visible=n;this.ia.jt()};y.K(A.prototype,"hide",A.prototype.jt);A.G={};A.G.gC=function(a){return"undefined"!=typeof a};A.G.push=function(a,b){a[a.length]=b};var Ua=navigator&&navigator.userAgent?navigator.userAgent.toLowerCase():l,Va=navigator&&navigator.platform?navigator.platform.toLowerCase():l;A.platform={};
y.K(A,"platform",A.platform);A.platform.ho=Va?/win/.test(Va):/win/.test(Ua);y.K(A.platform,"isWin",A.platform.ho);A.platform.PK=!A.platform.ho&&(Va?/mac/.test(Va):/mac/.test(Ua));y.K(A.platform,"isMac",A.platform.PK);A.platform.WG="undefined"!=typeof document.getElementById&&"undefined"!=typeof document.getElementsByTagName&&"undefiend"!=typeof document.createElement;y.K(A.platform,"hasDom",A.platform.WG);A.platform.fJ=/webkit/.test(Ua)?parseFloat(Ua.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):n;
y.K(A.platform,"webKit",A.platform.fJ);A.platform.zq=/msie/.test(Ua);y.K(A.platform,"isIE",A.platform.zq);A.platform.mH=/firefox/.test(Ua);y.K(A.platform,"isFirefox",A.platform.mH);A.platform.protocol="https:"==location.protocol?"https:":"http:";y.K(A.platform,"protocol",A.platform.protocol);
A.nH=function(){A.platform.Ah=[0,0,0];var a;if(navigator.plugins&&"object"==typeof navigator.plugins["Shockwave Flash"]){if((a=navigator.plugins["Shockwave Flash"].description)&&(!navigator.mimeTypes||!navigator.mimeTypes[["application/x-shockwave-flash"]]||navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin))a=a.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),A.platform.Ah[0]=parseInt(a.replace(/^(.*)\..*$/,"$1"),10),A.platform.Ah[1]=parseInt(a.replace(/^.*\.(.*)\s.*$/,"$1"),10),A.platform.Ah[2]=
/[a-zA-Z]/.test(a)?parseInt(a.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if("undefined"!=typeof window.ActiveXObject)try{var b=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(b&&(a=b.GetVariable("$version")))a=a.split(" ")[1].split(","),A.platform.Ah=[parseInt(a[0],10),parseInt(a[1],10),parseInt(a[2],10)]}catch(c){}return A.platform.Ah!=l&&9<=Number(A.platform.Ah[0])};y.K(A,"isFlashPlayerValidVersion",A.nH);A.platform.hC=A.nH();y.K(A.platform,"hasRequiredVersion",A.platform.hC);
A.platform.Ah=A.platform.Ah;y.K(A.platform,"flashPlayerVersion",A.platform.Ah);A.platform.Mj=A.platform.hC&&A.platform.zq&&A.platform.ho;y.K(A.platform,"needFormFix",A.platform.Mj);A.platform.Mj&&(A.platform.Mj=9==Number(A.platform.Ah[0]),A.platform.Mj=A.platform.Mj&&0==Number(A.platform.Ah[1]),A.platform.Mj=A.platform.Mj&&115>Number(A.platform.Ah[2]));A.jB=[];A.oL=function(a){y.rx(a)&&A.jB.push(a)};y.K(A,"ready",A.oL);
A.WK=function(a){if(a==l||a==g)a=A.pK();var a=a+"AnyChartHTML5.js",b=new Ba;b.TE=i;y.B.hb(b,"complete",A.iI,l,A);y.B.hb(b,["error","abort"],A.hI,l,A);b.send(a,"GET",l,"anychart.com")};y.K(A,"loadHTML5Engine",A.WK);A.iI=function(a){var a=a.target,b;try{b=a.hc?a.hc.responseText:""}catch(c){b=""}eval(b.toString());b=A.jB.length;for(var e=0;e<b;e++)A.jB[e]();A.UJ(a)};A.hI=function(){d(Error("Can not find AnyChart html5 engine in JS folder."))};
A.UJ=function(a){y.B.Lc(a,"complete",A.iI,l,A);y.B.Lc(a,["error","abort"],A.hI,l,A)};A.pK=function(){for(var a=y.global.document.getElementsByTagName("script"),b=a.length-1;b>=0;--b){var c=a[b].src,e=c.lastIndexOf("?"),e=e==-1?c.length:e,c=c.substr(0,e),f=c.split("/"),f=f[f.length-1].toLowerCase(),h=f.length;if(f.indexOf("anychart")!=-1&&f.substr(h-3,3)==".js")return c.substr(0,e-h)}return l};A.G.attachEvent=function(a,b,c){a.attachEvent(b,c);A.G.push(A.G.HO,[a,b,c])};
A.G.uJ=function(a,b){if(A.G.gC(window.addEventListener))window.addEventListener(a,b,n);else if(A.G.gC(document.addEventListener))document.addEventListener(a,b,n);else if(A.G.gC(window.attachEvent))A.G.attachEvent(window,"on"+a,b);else if(typeof window["on"+a]=="function"){var c=window["on"+a];window["on"+a]=function(){c();b()}}else window["on"+a]=b};y.eg("AnyChart.utils.addGlobalEventListener",A.G.uJ);A.G.xq=n;A.G.WA=[];A.G.tJ=function(a){A.G.xq?a():A.G.WA.push(a)};
A.G.Tp=function(){if(!A.G.xq){try{var a=document.getElementsByTagName("body")[0].appendChild(document.createElement("span"));a.parentNode.removeChild(a)}catch(b){return}A.G.xq=i;for(var a=A.G.WA.length,c=0;c<a;c++)A.G.WA[c]()}};
A.G.qL=function(){if(A.platform.WG){typeof document.readyState!="undefined"&&(document.readyState=="complete"||document.getElementsByTagName("body")[0]||document.body)&&A.G.Tp();if(!A.G.xq){document.addEventListener&&document.addEventListener("DOMContentLoaded",A.G.Tp,n);if(A.platform.zq&&A.platform.ho){document.attachEvent("onreadystatechange",function(){if(document.readyState=="complete"){document.detachEvent("onreadystatechange",arguments.callee);A.G.Tp()}});window==top&&function(){if(!A.G.xq){try{document.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,
0);return}A.G.Tp()}}()}A.platform.fJ&&function(){A.G.xq||(/loaded|complete/.test(document.readyState)?A.G.Tp():setTimeout(arguments.callee,0))}();y.B.hb(window,"load",A.G.Tp)}}};A.G.qL();A.dispatchEvent=function(a,b){A.tF(a)&&b!=l&&A.Dp[a].dispatchEvent(b)};y.K(A,"dispatchEvent",A.dispatchEvent);
function Wa(a){switch(a.renderingType){case "svg":return new window.anychart.render.svg.SVGRenderer;case "flash":return new Ka;default:case "flashPreferred":return A.platform.hasRequiredVersion?new Ka:new window.anychart.render.svg.SVGRenderer;case "svgPreferred":return window.SVGAngle!=g?new window.anychart.render.svg.SVGRenderer:new Ka}}A.rL=function(a){a.id=a.id==g?"__AnyChart___"+A.gs.length:a.id;A.Dp[a.id]=a;A.gs.push(a)};A.tF=function(a){return a&&A.Dp&&A.Dp[a]};
A.rK=function(a){return A.tF(a)?A.Dp[a]:l};y.K(A,"getChartById",A.rK);A.bK=function(a,b){A.Pp(a,b)};y.K(A,"disposeFlashObject",A.bK);A.Pp=function(a,b){a.Pp(a,b)};y.K(A,"disposeVisual",A.Pp);A.prototype.Pp=function(a,b){this.ia.Pp(a,b)};A.G.Le={};y.eg("AnyChart.utils.JSConverter",A.G.Le);A.G.Le.CC=function(a){a=typeof a;return a=="string"||a=="number"||a=="boolean"};y.K(A.G.Le,"isAttribute",A.G.Le.CC);A.G.Le.isArray=function(a){return typeof a!="string"&&typeof a.length!="undefined"};
y.K(A.G.Le,"isArray",A.G.Le.isArray);A.G.Le.HJ=function(a){return A.G.Le.HA("anychart",a)};y.K(A.G.Le,"convert",A.G.Le.HJ);
A.G.Le.HA=function(a,b){var c,e,f="<"+a;if(typeof b.functionName!="undefined"){b["function"]=b.functionName;delete b.functionName}for(c in b)c!="format"&&c!="text"&&c!="custom_attribute_value"&&c!="attr"&&A.G.Le.CC(b[c])&&(f=f+(" "+c+'="'+b[c]+'"'));f=f+">";for(c in b)if(c=="arg"&&A.G.Le.isArray(b[c])){var h=b[c];for(e=0;e<h.length;e++)f=f+("<arg><![CDATA["+h[e]+"]]\></arg>")}else if(c=="custom_attribute_value"||c=="attr")f=f+("<![CDATA["+b[c]+"]]\>");else if(c=="format"||c=="text")f=f+("<"+c+"><![CDATA["+
b[c]+"]]\></"+c+">");else if(A.G.Le.isArray(b[c])){h=b[c];for(e=0;e<h.length;e++)f=f+A.G.Le.HA(c,h[e])}else A.G.Le.CC(b[c])||(f=f+A.G.Le.HA(c,b[c]));return f+("</"+a+">")};A.messages={};A.messages.preloaderInit=" ";A.messages.preloaderLoading="Loading... ";A.messages.init="Initializing...";A.messages.loadingConfig="Loading config...";A.messages.loadingResources="Loading resources...";A.messages.loadingTemplates="Loading templates...";A.messages.noData="No Data";A.messages.waitingForData="Waiting for data...";
A.watermark=l;A.prototype.aL={};y.K(A.prototype,"messages",A.prototype.aL);A.prototype.messages.preloaderInit=l;A.prototype.messages.preloaderLoading=l;A.prototype.messages.init=l;A.prototype.messages.loadingConfig=l;A.prototype.messages.loadingResources=l;A.prototype.messages.loadingTemplates=l;A.prototype.messages.noData=l;A.prototype.messages.waitingForData=l;A.prototype.addEventListener=function(a,b){this.Hd[a]==l&&(this.Hd[a]=[]);this.Hd[a].push(b)};y.K(A.prototype,"addEventListener",A.prototype.addEventListener);
A.prototype.removeEventListener=function(a,b){if(!(this.Hd==l||this.Hd[a]==l)){for(var c=-1,e=0;e<this.Hd[a].length;e++)if(this.Hd[a][e]==b){c=e;break}c!=-1&&this.Hd[a].splice(c,1)}};y.K(A.prototype,"removeEventListener",A.prototype.removeEventListener);A.prototype.dispatchEvent=function(a){if(!(a==l||a.type==l)){a.type=="create"?this.ia.eI():a.type=="draw"&&this.ia.fI();a.target=this;if(!(this.Hd==l||this.Hd[a.type]==l))for(var b=this.Hd[a.type].length,c=0;c<b;c++)this.Hd[a.type][c](a)}};
y.K(A.prototype,"dispatchEvent",A.prototype.dispatchEvent);A.prototype.sn=function(){return this.ia.sn()};y.K(A.prototype,"canWrite",A.prototype.sn);A.prototype.write=function(a){this.ia=Wa(this);this.ia.Un(this);if(this.sn()){if(a==g){a="__chart_generated_container__"+this.id;document.write('<div id="'+a+'"></div>')}var b=this;A.G.tJ(function(){typeof a=="string"?Xa(b,document.getElementById(a)):Xa(b,a)})}};y.K(A.prototype,"write",A.prototype.write);
function Xa(a,b){a.Hj=a.ia.write(b);a.Hj&&a.bs()&&(a.xmlFile!=l?a.Yh(a.xmlFile):a.jsonFile!=l?a.Rm(a.jsonFile):a.xmlData!=l?a.xu(a.xmlData):a.jsonData!=l&&a.Oi(a.jsonData))}A.prototype.bs=function(){return this.ia.bs()};y.K(A.prototype,"canSetConfigAfterWrite",A.prototype.bs);A.prototype.xz=function(){this.ia.xz()};y.K(A.prototype,"updatePrintForFirefox",A.prototype.xz);A.prototype.Uo=function(a,b){this.width=a;this.height=b;this.ia.Uo(a,b)};y.K(A.prototype,"setSize",A.prototype.Uo);
y.eg("AnyChart.prototype.resize",A.prototype.Uo);A.prototype.remove=function(){this.ia.remove()};y.K(A.prototype,"remove",A.prototype.remove);A.prototype.clear=function(){this.ia.clear()};y.K(A.prototype,"clear",A.prototype.clear);A.prototype.refresh=function(){this.ia.refresh()};y.K(A.prototype,"refresh",A.prototype.refresh);A.prototype.xr=function(a,b){this.ia.xr(a,b)};y.K(A.prototype,"updateData",A.prototype.xr);A.prototype.Ny=function(a){this.ia.Ny(a)};y.K(A.prototype,"setLoading",A.prototype.Ny);
A.prototype.Fw=function(){return this.ia.Fw()};y.K(A.prototype,"getInformation",A.prototype.Fw);A.prototype.Yh=function(a){this.xmlFile=a;this.Hj&&this.ia.Yh(a)};y.K(A.prototype,"setXMLFile",A.prototype.Yh);A.prototype.ih=function(a){this.xmlData=""+a;this.Hj&&this.ia.ih(this.xmlData)};y.K(A.prototype,"setXMLData",A.prototype.ih);A.prototype.xu=function(a){this.Hj&&this.ia.xu(a)};y.K(A.prototype,"setXMLDataFromString",A.prototype.xu);A.prototype.Vy=function(a){this.Hj&&this.ia.Vy(a)};
y.K(A.prototype,"setXMLDataFromURL",A.prototype.Vy);A.prototype.Vo=function(a,b){this.ia.Vo(a,b)};y.K(A.prototype,"setViewXMLFile",A.prototype.Vo);A.prototype.Ry=function(a,b){this.ia.Ry(a,b)};y.K(A.prototype,"setViewData",A.prototype.Ry);A.prototype.Rm=function(a){this.jsonFile=a;this.Hj&&this.ia.Rm(a)};y.K(A.prototype,"setJSONFile",A.prototype.Rm);A.prototype.Oi=function(a){this.jsonData=a;this.Hj&&this.ia.Oi(this.jsonData)};y.K(A.prototype,"setJSONData",A.prototype.Oi);
y.eg("AnyChart.prototype.setJSData",A.prototype.Oi);A.prototype.setData=function(a){if(a!=l){for(var b=""+a;b.charAt(0)==" "&&b.length>0;)b=b.substr(1);if(b.charAt(0)=="<"){this.xmlData=""+a;this.Hj&&this.ia.ih(this.xmlData)}else{this.jsonData=a;this.Hj&&this.ia.Oi(this.jsonData)}}};y.K(A.prototype,"setData",A.prototype.setData);A.prototype.rd=function(a,b){this.ia.rd(a,b)};y.K(A.prototype,"addPoint",A.prototype.rd);A.prototype.bj=function(a,b,c){this.ia.bj(a,b,c)};y.K(A.prototype,"addPointAt",A.prototype.bj);
A.prototype.Rj=function(a,b){this.ia.Rj(a,b)};y.K(A.prototype,"removePoint",A.prototype.Rj);A.prototype.ak=function(a,b,c){this.ia.ak(a,b,c)};y.K(A.prototype,"updatePoint",A.prototype.ak);A.prototype.bk=function(a,b,c){this.ia.bk(a,b,c)};y.K(A.prototype,"updatePointData",A.prototype.bk);A.prototype.Cj=function(a,b,c){this.ia.Cj(a,b,c)};y.K(A.prototype,"highlightPoint",A.prototype.Cj);A.prototype.Ki=function(a,b,c){this.ia.Ki(a,b,c)};y.K(A.prototype,"selectPoint",A.prototype.Ki);
A.prototype.wz=function(a,b,c,e){this.ia.wz(a,b,c,e)};y.K(A.prototype,"updatePointWithAnimation",A.prototype.wz);A.prototype.fz=function(){this.ia.fz()};y.K(A.prototype,"startPointsAnimation",A.prototype.fz);A.prototype.cj=function(a){this.ia.cj(a)};y.K(A.prototype,"addSeries",A.prototype.cj);A.prototype.dj=function(a,b){this.ia.dj(a,b)};y.K(A.prototype,"addSeriesAt",A.prototype.dj);A.prototype.Sj=function(a){this.ia.Sj(a)};y.K(A.prototype,"removeSeries",A.prototype.Sj);
A.prototype.ck=function(a,b){this.ia.ck(a,b)};y.K(A.prototype,"updateSeries",A.prototype.ck);A.prototype.Wj=function(a,b){this.ia.Wj(a,b)};y.K(A.prototype,"showSeries",A.prototype.Wj);A.prototype.Dj=function(a,b){this.ia.Dj(a,b)};y.K(A.prototype,"highlightSeries",A.prototype.Dj);A.prototype.Bj=function(a,b){this.ia.Bj(a,b)};y.K(A.prototype,"highlightCategory",A.prototype.Bj);A.prototype.bz=function(a,b){this.ia.bz(a,b)};y.K(A.prototype,"showAxisMarker",A.prototype.bz);
A.prototype.Vj=function(a,b){this.ia.Vj(a,b)};y.K(A.prototype,"setPlotCustomAttribute",A.prototype.Vj);A.prototype.Or=function(a,b,c){this.ia.Or(a,b,c)};y.K(A.prototype,"view_setPlotCustomAttribute",A.prototype.Or);A.prototype.Fr=function(a,b){this.ia.Fr(a,b)};y.K(A.prototype,"view_addSeries",A.prototype.Fr);A.prototype.Mr=function(a,b){this.ia.Mr(a,b)};y.K(A.prototype,"view_removeSeries",A.prototype.Mr);A.prototype.Gr=function(a,b,c){this.ia.Gr(a,b,c)};y.K(A.prototype,"view_addSeriesAt",A.prototype.Gr);
A.prototype.Rr=function(a,b,c){this.ia.Rr(a,b,c)};y.K(A.prototype,"view_updateSeries",A.prototype.Rr);A.prototype.Pr=function(a,b,c){this.ia.Pr(a,b,c)};y.K(A.prototype,"view_showSeries",A.prototype.Pr);A.prototype.Dr=function(a,b,c){this.ia.Dr(a,b,c)};y.K(A.prototype,"view_addPoint",A.prototype.Dr);A.prototype.Er=function(a,b,c,e){this.ia.Er(a,b,c,e)};y.K(A.prototype,"view_addPointAt",A.prototype.Er);A.prototype.Lr=function(a,b,c){this.ia.Lr(a,b,c)};y.K(A.prototype,"view_removePoint",A.prototype.Lr);
A.prototype.Qr=function(a,b,c,e){this.ia.Qr(a,b,c,e)};y.K(A.prototype,"view_updatePoint",A.prototype.Qr);A.prototype.Fz=function(a){this.ia.Fz(a)};y.K(A.prototype,"view_clear",A.prototype.Fz);A.prototype.Kr=function(a){this.ia.Kr(a)};y.K(A.prototype,"view_refresh",A.prototype.Kr);A.prototype.Jr=function(a,b,c){this.ia.Jr(a,b,c)};y.K(A.prototype,"view_highlightSeries",A.prototype.Jr);A.prototype.Ir=function(a,b,c,e){this.ia.Ir(a,b,c,e)};y.K(A.prototype,"view_highlightPoint",A.prototype.Ir);
A.prototype.Hr=function(a,b,c){this.ia.Hr(a,b,c)};y.K(A.prototype,"view_highlightCategory",A.prototype.Hr);A.prototype.Nr=function(a,b,c,e){this.ia.Nr(a,b,c,e)};y.K(A.prototype,"view_selectPoint",A.prototype.Nr);A.prototype.yr=function(a,b,c,e){this.ia.yr(a,b,c,e)};y.K(A.prototype,"updateViewPointData",A.prototype.yr);A.prototype.jq=function(a,b){if(a==l||a==g)a=NaN;if(b==l||b==g)b=NaN;return this.ia.jq(a,b)};y.K(A.prototype,"getPNG",A.prototype.jq);y.eg("AnyChart.prototype.getPNGImage",A.prototype.jq);
A.prototype.Sw=function(a,b){if(a==l||a==g)a=NaN;if(b==l||b==g)b=NaN;return this.ia.Sw(a,b)};y.K(A.prototype,"getPDF",A.prototype.Sw);A.prototype.ry=function(){this.ia.ry()};y.K(A.prototype,"printChart",A.prototype.ry);A.prototype.Fy=function(a,b){if(a==l||a==g)a=NaN;if(b==l||b==g)b=NaN;this.ia.Fy(a,b)};y.K(A.prototype,"saveAsImage",A.prototype.Fy);A.prototype.Gy=function(a,b){if(a==l||a==g)a=NaN;if(b==l||b==g)b=NaN;this.ia.Gy(a,b)};y.K(A.prototype,"saveAsPDF",A.prototype.Gy);A.prototype.Hy=function(a){this.ia.Hy(a)};
y.K(A.prototype,"scrollXTo",A.prototype.Hy);A.prototype.Iy=function(a){this.ia.Iy(a)};y.K(A.prototype,"scrollYTo",A.prototype.Iy);A.prototype.scrollTo=function(a,b){this.ia.scrollTo(a,b)};y.K(A.prototype,"scrollTo",A.prototype.scrollTo);A.prototype.Cz=function(a,b){this.ia.Cz(a,b)};y.K(A.prototype,"viewScrollXTo",A.prototype.Cz);A.prototype.Dz=function(a,b){this.ia.Dz(a,b)};y.K(A.prototype,"viewScrollYTo",A.prototype.Dz);A.prototype.Xw=function(){return this.ia.Xw()};
y.K(A.prototype,"getXScrollInfo",A.prototype.Xw);A.prototype.Yw=function(){return this.ia.Yw()};y.K(A.prototype,"getYScrollInfo",A.prototype.Yw);A.prototype.Vw=function(a){return this.ia.Vw(a)};y.K(A.prototype,"getViewXScrollInfo",A.prototype.Vw);A.prototype.Ww=function(a){return this.ia.Ww(a)};y.K(A.prototype,"getViewYScrollInfo",A.prototype.Ww);A.prototype.Wy=function(a){this.ia.Wy(a)};y.K(A.prototype,"setXZoom",A.prototype.Wy);A.prototype.Xy=function(a){this.ia.Xy(a)};
y.K(A.prototype,"setYZoom",A.prototype.Xy);A.prototype.Yy=function(a,b){this.ia.Yy(a,b)};y.K(A.prototype,"setZoom",A.prototype.Yy);A.prototype.Sy=function(a,b){this.ia.Sy(a,b)};y.K(A.prototype,"setViewXZoom",A.prototype.Sy);A.prototype.Ty=function(a,b){this.ia.Ty(a,b)};y.K(A.prototype,"setViewYZoom",A.prototype.Ty);A.prototype.Uy=function(a,b,c){this.ia.Uy(a,b,c)};y.K(A.prototype,"setViewZoom",A.prototype.Uy);A.prototype.rv=function(){this.ia.rv()};y.K(A.prototype,"animate",A.prototype.rv);
A.prototype.yc=function(a){return this.ia.yc(a)};y.K(A.prototype,"getSVG",A.prototype.yc);})()
